/*
 * YugabyteDB Anywhere APIs
 *
 * ALPHA - NOT FOR EXTERNAL USE
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// ConfDataTypeObject struct for ConfDataTypeObject
type ConfDataTypeObject struct {
	Name string `json:"name"`
}

// NewConfDataTypeObject instantiates a new ConfDataTypeObject object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfDataTypeObject(name string) *ConfDataTypeObject {
	this := ConfDataTypeObject{}
	this.Name = name
	return &this
}

// NewConfDataTypeObjectWithDefaults instantiates a new ConfDataTypeObject object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfDataTypeObjectWithDefaults() *ConfDataTypeObject {
	this := ConfDataTypeObject{}
	return &this
}

// GetName returns the Name field value
func (o *ConfDataTypeObject) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ConfDataTypeObject) GetNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ConfDataTypeObject) SetName(v string) {
	o.Name = v
}

func (o ConfDataTypeObject) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullableConfDataTypeObject struct {
	value *ConfDataTypeObject
	isSet bool
}

func (v NullableConfDataTypeObject) Get() *ConfDataTypeObject {
	return v.value
}

func (v *NullableConfDataTypeObject) Set(val *ConfDataTypeObject) {
	v.value = val
	v.isSet = true
}

func (v NullableConfDataTypeObject) IsSet() bool {
	return v.isSet
}

func (v *NullableConfDataTypeObject) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfDataTypeObject(val *ConfDataTypeObject) *NullableConfDataTypeObject {
	return &NullableConfDataTypeObject{value: val, isSet: true}
}

func (v NullableConfDataTypeObject) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfDataTypeObject) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


