/*
YugabyteDB Anywhere APIs

ALPHA - NOT FOR EXTERNAL USE

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ywclient

import (
	"encoding/json"
)

// checks if the MetricsExportConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MetricsExportConfig{}

// MetricsExportConfig Metrics Export Configuration
type MetricsExportConfig struct {
	// The level of metrics collection. Allowed values are: ALL, NORMAL, MINIMAL, OFF
	CollectionLevel *string `json:"collectionLevel,omitempty"`
	// Set of target types to include in scrape configuration. If not specified, all supported target types will be included.
	ScrapeConfigTargets []string `json:"scrapeConfigTargets,omitempty"`
	// Scrape interval in seconds. Applied on all scrape jobs commonly.
	ScrapeIntervalSeconds *int32 `json:"scrapeIntervalSeconds,omitempty"`
	// Scrape timeout in seconds. Applied on all scrape jobs commonly.
	ScrapeTimeoutSeconds *int32 `json:"scrapeTimeoutSeconds,omitempty"`
	// List of universe metrics exporter configurations. If empty, no metrics will be sent anywhere.
	UniverseMetricsExporterConfig []UniverseMetricsExporterConfig `json:"universeMetricsExporterConfig"`
}

type _MetricsExportConfig MetricsExportConfig

// NewMetricsExportConfig instantiates a new MetricsExportConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMetricsExportConfig(universeMetricsExporterConfig []UniverseMetricsExporterConfig) *MetricsExportConfig {
	this := MetricsExportConfig{}
	this.UniverseMetricsExporterConfig = universeMetricsExporterConfig
	return &this
}

// NewMetricsExportConfigWithDefaults instantiates a new MetricsExportConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMetricsExportConfigWithDefaults() *MetricsExportConfig {
	this := MetricsExportConfig{}
	return &this
}

// GetCollectionLevel returns the CollectionLevel field value if set, zero value otherwise.
func (o *MetricsExportConfig) GetCollectionLevel() string {
	if o == nil || IsNil(o.CollectionLevel) {
		var ret string
		return ret
	}
	return *o.CollectionLevel
}

// GetCollectionLevelOk returns a tuple with the CollectionLevel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricsExportConfig) GetCollectionLevelOk() (*string, bool) {
	if o == nil || IsNil(o.CollectionLevel) {
		return nil, false
	}
	return o.CollectionLevel, true
}

// HasCollectionLevel returns a boolean if a field has been set.
func (o *MetricsExportConfig) HasCollectionLevel() bool {
	if o != nil && !IsNil(o.CollectionLevel) {
		return true
	}

	return false
}

// SetCollectionLevel gets a reference to the given string and assigns it to the CollectionLevel field.
func (o *MetricsExportConfig) SetCollectionLevel(v string) {
	o.CollectionLevel = &v
}

// GetScrapeConfigTargets returns the ScrapeConfigTargets field value if set, zero value otherwise.
func (o *MetricsExportConfig) GetScrapeConfigTargets() []string {
	if o == nil || IsNil(o.ScrapeConfigTargets) {
		var ret []string
		return ret
	}
	return o.ScrapeConfigTargets
}

// GetScrapeConfigTargetsOk returns a tuple with the ScrapeConfigTargets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricsExportConfig) GetScrapeConfigTargetsOk() ([]string, bool) {
	if o == nil || IsNil(o.ScrapeConfigTargets) {
		return nil, false
	}
	return o.ScrapeConfigTargets, true
}

// HasScrapeConfigTargets returns a boolean if a field has been set.
func (o *MetricsExportConfig) HasScrapeConfigTargets() bool {
	if o != nil && !IsNil(o.ScrapeConfigTargets) {
		return true
	}

	return false
}

// SetScrapeConfigTargets gets a reference to the given []string and assigns it to the ScrapeConfigTargets field.
func (o *MetricsExportConfig) SetScrapeConfigTargets(v []string) {
	o.ScrapeConfigTargets = v
}

// GetScrapeIntervalSeconds returns the ScrapeIntervalSeconds field value if set, zero value otherwise.
func (o *MetricsExportConfig) GetScrapeIntervalSeconds() int32 {
	if o == nil || IsNil(o.ScrapeIntervalSeconds) {
		var ret int32
		return ret
	}
	return *o.ScrapeIntervalSeconds
}

// GetScrapeIntervalSecondsOk returns a tuple with the ScrapeIntervalSeconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricsExportConfig) GetScrapeIntervalSecondsOk() (*int32, bool) {
	if o == nil || IsNil(o.ScrapeIntervalSeconds) {
		return nil, false
	}
	return o.ScrapeIntervalSeconds, true
}

// HasScrapeIntervalSeconds returns a boolean if a field has been set.
func (o *MetricsExportConfig) HasScrapeIntervalSeconds() bool {
	if o != nil && !IsNil(o.ScrapeIntervalSeconds) {
		return true
	}

	return false
}

// SetScrapeIntervalSeconds gets a reference to the given int32 and assigns it to the ScrapeIntervalSeconds field.
func (o *MetricsExportConfig) SetScrapeIntervalSeconds(v int32) {
	o.ScrapeIntervalSeconds = &v
}

// GetScrapeTimeoutSeconds returns the ScrapeTimeoutSeconds field value if set, zero value otherwise.
func (o *MetricsExportConfig) GetScrapeTimeoutSeconds() int32 {
	if o == nil || IsNil(o.ScrapeTimeoutSeconds) {
		var ret int32
		return ret
	}
	return *o.ScrapeTimeoutSeconds
}

// GetScrapeTimeoutSecondsOk returns a tuple with the ScrapeTimeoutSeconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricsExportConfig) GetScrapeTimeoutSecondsOk() (*int32, bool) {
	if o == nil || IsNil(o.ScrapeTimeoutSeconds) {
		return nil, false
	}
	return o.ScrapeTimeoutSeconds, true
}

// HasScrapeTimeoutSeconds returns a boolean if a field has been set.
func (o *MetricsExportConfig) HasScrapeTimeoutSeconds() bool {
	if o != nil && !IsNil(o.ScrapeTimeoutSeconds) {
		return true
	}

	return false
}

// SetScrapeTimeoutSeconds gets a reference to the given int32 and assigns it to the ScrapeTimeoutSeconds field.
func (o *MetricsExportConfig) SetScrapeTimeoutSeconds(v int32) {
	o.ScrapeTimeoutSeconds = &v
}

// GetUniverseMetricsExporterConfig returns the UniverseMetricsExporterConfig field value
func (o *MetricsExportConfig) GetUniverseMetricsExporterConfig() []UniverseMetricsExporterConfig {
	if o == nil {
		var ret []UniverseMetricsExporterConfig
		return ret
	}

	return o.UniverseMetricsExporterConfig
}

// GetUniverseMetricsExporterConfigOk returns a tuple with the UniverseMetricsExporterConfig field value
// and a boolean to check if the value has been set.
func (o *MetricsExportConfig) GetUniverseMetricsExporterConfigOk() ([]UniverseMetricsExporterConfig, bool) {
	if o == nil {
		return nil, false
	}
	return o.UniverseMetricsExporterConfig, true
}

// SetUniverseMetricsExporterConfig sets field value
func (o *MetricsExportConfig) SetUniverseMetricsExporterConfig(v []UniverseMetricsExporterConfig) {
	o.UniverseMetricsExporterConfig = v
}

func (o MetricsExportConfig) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MetricsExportConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CollectionLevel) {
		toSerialize["collectionLevel"] = o.CollectionLevel
	}
	if !IsNil(o.ScrapeConfigTargets) {
		toSerialize["scrapeConfigTargets"] = o.ScrapeConfigTargets
	}
	if !IsNil(o.ScrapeIntervalSeconds) {
		toSerialize["scrapeIntervalSeconds"] = o.ScrapeIntervalSeconds
	}
	if !IsNil(o.ScrapeTimeoutSeconds) {
		toSerialize["scrapeTimeoutSeconds"] = o.ScrapeTimeoutSeconds
	}
	toSerialize["universeMetricsExporterConfig"] = o.UniverseMetricsExporterConfig
	return toSerialize, nil
}

type NullableMetricsExportConfig struct {
	value *MetricsExportConfig
	isSet bool
}

func (v NullableMetricsExportConfig) Get() *MetricsExportConfig {
	return v.value
}

func (v *NullableMetricsExportConfig) Set(val *MetricsExportConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableMetricsExportConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableMetricsExportConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMetricsExportConfig(val *MetricsExportConfig) *NullableMetricsExportConfig {
	return &NullableMetricsExportConfig{value: val, isSet: true}
}

func (v NullableMetricsExportConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMetricsExportConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
