/*
YugabyteDB Anywhere APIs

ALPHA - NOT FOR EXTERNAL USE

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ywclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PresetThrottleValues type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PresetThrottleValues{}

// PresetThrottleValues struct for PresetThrottleValues
type PresetThrottleValues struct {
	DefaultValue int64 `json:"defaultValue"`
	MaxValue int64 `json:"maxValue"`
	MinValue int64 `json:"minValue"`
}

type _PresetThrottleValues PresetThrottleValues

// NewPresetThrottleValues instantiates a new PresetThrottleValues object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPresetThrottleValues(defaultValue int64, maxValue int64, minValue int64) *PresetThrottleValues {
	this := PresetThrottleValues{}
	this.DefaultValue = defaultValue
	this.MaxValue = maxValue
	this.MinValue = minValue
	return &this
}

// NewPresetThrottleValuesWithDefaults instantiates a new PresetThrottleValues object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPresetThrottleValuesWithDefaults() *PresetThrottleValues {
	this := PresetThrottleValues{}
	return &this
}

// GetDefaultValue returns the DefaultValue field value
func (o *PresetThrottleValues) GetDefaultValue() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.DefaultValue
}

// GetDefaultValueOk returns a tuple with the DefaultValue field value
// and a boolean to check if the value has been set.
func (o *PresetThrottleValues) GetDefaultValueOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DefaultValue, true
}

// SetDefaultValue sets field value
func (o *PresetThrottleValues) SetDefaultValue(v int64) {
	o.DefaultValue = v
}

// GetMaxValue returns the MaxValue field value
func (o *PresetThrottleValues) GetMaxValue() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.MaxValue
}

// GetMaxValueOk returns a tuple with the MaxValue field value
// and a boolean to check if the value has been set.
func (o *PresetThrottleValues) GetMaxValueOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaxValue, true
}

// SetMaxValue sets field value
func (o *PresetThrottleValues) SetMaxValue(v int64) {
	o.MaxValue = v
}

// GetMinValue returns the MinValue field value
func (o *PresetThrottleValues) GetMinValue() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.MinValue
}

// GetMinValueOk returns a tuple with the MinValue field value
// and a boolean to check if the value has been set.
func (o *PresetThrottleValues) GetMinValueOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MinValue, true
}

// SetMinValue sets field value
func (o *PresetThrottleValues) SetMinValue(v int64) {
	o.MinValue = v
}

func (o PresetThrottleValues) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PresetThrottleValues) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["defaultValue"] = o.DefaultValue
	toSerialize["maxValue"] = o.MaxValue
	toSerialize["minValue"] = o.MinValue
	return toSerialize, nil
}

type NullablePresetThrottleValues struct {
	value *PresetThrottleValues
	isSet bool
}

func (v NullablePresetThrottleValues) Get() *PresetThrottleValues {
	return v.value
}

func (v *NullablePresetThrottleValues) Set(val *PresetThrottleValues) {
	v.value = val
	v.isSet = true
}

func (v NullablePresetThrottleValues) IsSet() bool {
	return v.isSet
}

func (v *NullablePresetThrottleValues) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePresetThrottleValues(val *PresetThrottleValues) *NullablePresetThrottleValues {
	return &NullablePresetThrottleValues{value: val, isSet: true}
}

func (v NullablePresetThrottleValues) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePresetThrottleValues) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


