/*
YugabyteDB Anywhere APIs

ALPHA - NOT FOR EXTERNAL USE

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ywclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PerformanceRecommendationPagedResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PerformanceRecommendationPagedResponse{}

// PerformanceRecommendationPagedResponse struct for PerformanceRecommendationPagedResponse
type PerformanceRecommendationPagedResponse struct {
	Entities []PerformanceRecommendation `json:"entities"`
	HasNext bool `json:"hasNext"`
	HasPrev bool `json:"hasPrev"`
	TotalCount int32 `json:"totalCount"`
}

type _PerformanceRecommendationPagedResponse PerformanceRecommendationPagedResponse

// NewPerformanceRecommendationPagedResponse instantiates a new PerformanceRecommendationPagedResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPerformanceRecommendationPagedResponse(entities []PerformanceRecommendation, hasNext bool, hasPrev bool, totalCount int32) *PerformanceRecommendationPagedResponse {
	this := PerformanceRecommendationPagedResponse{}
	this.Entities = entities
	this.HasNext = hasNext
	this.HasPrev = hasPrev
	this.TotalCount = totalCount
	return &this
}

// NewPerformanceRecommendationPagedResponseWithDefaults instantiates a new PerformanceRecommendationPagedResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPerformanceRecommendationPagedResponseWithDefaults() *PerformanceRecommendationPagedResponse {
	this := PerformanceRecommendationPagedResponse{}
	return &this
}

// GetEntities returns the Entities field value
func (o *PerformanceRecommendationPagedResponse) GetEntities() []PerformanceRecommendation {
	if o == nil {
		var ret []PerformanceRecommendation
		return ret
	}

	return o.Entities
}

// GetEntitiesOk returns a tuple with the Entities field value
// and a boolean to check if the value has been set.
func (o *PerformanceRecommendationPagedResponse) GetEntitiesOk() ([]PerformanceRecommendation, bool) {
	if o == nil {
		return nil, false
	}
	return o.Entities, true
}

// SetEntities sets field value
func (o *PerformanceRecommendationPagedResponse) SetEntities(v []PerformanceRecommendation) {
	o.Entities = v
}

// GetHasNext returns the HasNext field value
func (o *PerformanceRecommendationPagedResponse) GetHasNext() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HasNext
}

// GetHasNextOk returns a tuple with the HasNext field value
// and a boolean to check if the value has been set.
func (o *PerformanceRecommendationPagedResponse) GetHasNextOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HasNext, true
}

// SetHasNext sets field value
func (o *PerformanceRecommendationPagedResponse) SetHasNext(v bool) {
	o.HasNext = v
}

// GetHasPrev returns the HasPrev field value
func (o *PerformanceRecommendationPagedResponse) GetHasPrev() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HasPrev
}

// GetHasPrevOk returns a tuple with the HasPrev field value
// and a boolean to check if the value has been set.
func (o *PerformanceRecommendationPagedResponse) GetHasPrevOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HasPrev, true
}

// SetHasPrev sets field value
func (o *PerformanceRecommendationPagedResponse) SetHasPrev(v bool) {
	o.HasPrev = v
}

// GetTotalCount returns the TotalCount field value
func (o *PerformanceRecommendationPagedResponse) GetTotalCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalCount
}

// GetTotalCountOk returns a tuple with the TotalCount field value
// and a boolean to check if the value has been set.
func (o *PerformanceRecommendationPagedResponse) GetTotalCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalCount, true
}

// SetTotalCount sets field value
func (o *PerformanceRecommendationPagedResponse) SetTotalCount(v int32) {
	o.TotalCount = v
}

func (o PerformanceRecommendationPagedResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PerformanceRecommendationPagedResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["entities"] = o.Entities
	toSerialize["hasNext"] = o.HasNext
	toSerialize["hasPrev"] = o.HasPrev
	toSerialize["totalCount"] = o.TotalCount
	return toSerialize, nil
}

type NullablePerformanceRecommendationPagedResponse struct {
	value *PerformanceRecommendationPagedResponse
	isSet bool
}

func (v NullablePerformanceRecommendationPagedResponse) Get() *PerformanceRecommendationPagedResponse {
	return v.value
}

func (v *NullablePerformanceRecommendationPagedResponse) Set(val *PerformanceRecommendationPagedResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePerformanceRecommendationPagedResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePerformanceRecommendationPagedResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePerformanceRecommendationPagedResponse(val *PerformanceRecommendationPagedResponse) *NullablePerformanceRecommendationPagedResponse {
	return &NullablePerformanceRecommendationPagedResponse{value: val, isSet: true}
}

func (v NullablePerformanceRecommendationPagedResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePerformanceRecommendationPagedResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


