/*
YugabyteDB Anywhere APIs

ALPHA - NOT FOR EXTERNAL USE

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ywclient

import (
	"encoding/json"
)

// checks if the CustomerCountResp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustomerCountResp{}

// CustomerCountResp struct for CustomerCountResp
type CustomerCountResp struct {
	Count int32 `json:"count"`
}

type _CustomerCountResp CustomerCountResp

// NewCustomerCountResp instantiates a new CustomerCountResp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomerCountResp(count int32) *CustomerCountResp {
	this := CustomerCountResp{}
	this.Count = count
	return &this
}

// NewCustomerCountRespWithDefaults instantiates a new CustomerCountResp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomerCountRespWithDefaults() *CustomerCountResp {
	this := CustomerCountResp{}
	return &this
}

// GetCount returns the Count field value
func (o *CustomerCountResp) GetCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *CustomerCountResp) GetCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *CustomerCountResp) SetCount(v int32) {
	o.Count = v
}

func (o CustomerCountResp) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustomerCountResp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["count"] = o.Count
	return toSerialize, nil
}

type NullableCustomerCountResp struct {
	value *CustomerCountResp
	isSet bool
}

func (v NullableCustomerCountResp) Get() *CustomerCountResp {
	return v.value
}

func (v *NullableCustomerCountResp) Set(val *CustomerCountResp) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomerCountResp) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomerCountResp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomerCountResp(val *CustomerCountResp) *NullableCustomerCountResp {
	return &NullableCustomerCountResp{value: val, isSet: true}
}

func (v NullableCustomerCountResp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomerCountResp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
