/*
YugabyteDB Anywhere APIs

ALPHA - NOT FOR EXTERNAL USE

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ywclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RoleBindingFormData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RoleBindingFormData{}

// RoleBindingFormData Role Binding form metadata
type RoleBindingFormData struct {
	// List of roles and resource groups defined.
	RoleResourceDefinitions []RoleResourceDefinition `json:"roleResourceDefinitions"`
}

type _RoleBindingFormData RoleBindingFormData

// NewRoleBindingFormData instantiates a new RoleBindingFormData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRoleBindingFormData(roleResourceDefinitions []RoleResourceDefinition) *RoleBindingFormData {
	this := RoleBindingFormData{}
	this.RoleResourceDefinitions = roleResourceDefinitions
	return &this
}

// NewRoleBindingFormDataWithDefaults instantiates a new RoleBindingFormData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRoleBindingFormDataWithDefaults() *RoleBindingFormData {
	this := RoleBindingFormData{}
	return &this
}

// GetRoleResourceDefinitions returns the RoleResourceDefinitions field value
func (o *RoleBindingFormData) GetRoleResourceDefinitions() []RoleResourceDefinition {
	if o == nil {
		var ret []RoleResourceDefinition
		return ret
	}

	return o.RoleResourceDefinitions
}

// GetRoleResourceDefinitionsOk returns a tuple with the RoleResourceDefinitions field value
// and a boolean to check if the value has been set.
func (o *RoleBindingFormData) GetRoleResourceDefinitionsOk() ([]RoleResourceDefinition, bool) {
	if o == nil {
		return nil, false
	}
	return o.RoleResourceDefinitions, true
}

// SetRoleResourceDefinitions sets field value
func (o *RoleBindingFormData) SetRoleResourceDefinitions(v []RoleResourceDefinition) {
	o.RoleResourceDefinitions = v
}

func (o RoleBindingFormData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RoleBindingFormData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["roleResourceDefinitions"] = o.RoleResourceDefinitions
	return toSerialize, nil
}

func (o *RoleBindingFormData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"roleResourceDefinitions",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRoleBindingFormData := _RoleBindingFormData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRoleBindingFormData)

	if err != nil {
		return err
	}

	*o = RoleBindingFormData(varRoleBindingFormData)

	return err
}

type NullableRoleBindingFormData struct {
	value *RoleBindingFormData
	isSet bool
}

func (v NullableRoleBindingFormData) Get() *RoleBindingFormData {
	return v.value
}

func (v *NullableRoleBindingFormData) Set(val *RoleBindingFormData) {
	v.value = val
	v.isSet = true
}

func (v NullableRoleBindingFormData) IsSet() bool {
	return v.isSet
}

func (v *NullableRoleBindingFormData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRoleBindingFormData(val *RoleBindingFormData) *NullableRoleBindingFormData {
	return &NullableRoleBindingFormData{value: val, isSet: true}
}

func (v NullableRoleBindingFormData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRoleBindingFormData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


