/*
 * YugabyteDB Anywhere APIs
 *
 * ALPHA - NOT FOR EXTERNAL USE
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ywclient

import (
	"encoding/json"
)

// EditBackupScheduleParams Info to edit the schedule params for backups
type EditBackupScheduleParams struct {
	// Cron expression for scheduling
	CronExpression *string `json:"cronExpression,omitempty"`
	// Frequency of the schedule
	Frequency *int64 `json:"frequency,omitempty"`
	// Time Unit for frequency
	FrequencyTimeUnit *string `json:"frequencyTimeUnit,omitempty"`
	// State of the schedule
	Status *string `json:"status,omitempty"`
}

// NewEditBackupScheduleParams instantiates a new EditBackupScheduleParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEditBackupScheduleParams() *EditBackupScheduleParams {
	this := EditBackupScheduleParams{}
	return &this
}

// NewEditBackupScheduleParamsWithDefaults instantiates a new EditBackupScheduleParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEditBackupScheduleParamsWithDefaults() *EditBackupScheduleParams {
	this := EditBackupScheduleParams{}
	return &this
}

// GetCronExpression returns the CronExpression field value if set, zero value otherwise.
func (o *EditBackupScheduleParams) GetCronExpression() string {
	if o == nil || o.CronExpression == nil {
		var ret string
		return ret
	}
	return *o.CronExpression
}

// GetCronExpressionOk returns a tuple with the CronExpression field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditBackupScheduleParams) GetCronExpressionOk() (*string, bool) {
	if o == nil || o.CronExpression == nil {
		return nil, false
	}
	return o.CronExpression, true
}

// HasCronExpression returns a boolean if a field has been set.
func (o *EditBackupScheduleParams) HasCronExpression() bool {
	if o != nil && o.CronExpression != nil {
		return true
	}

	return false
}

// SetCronExpression gets a reference to the given string and assigns it to the CronExpression field.
func (o *EditBackupScheduleParams) SetCronExpression(v string) {
	o.CronExpression = &v
}

// GetFrequency returns the Frequency field value if set, zero value otherwise.
func (o *EditBackupScheduleParams) GetFrequency() int64 {
	if o == nil || o.Frequency == nil {
		var ret int64
		return ret
	}
	return *o.Frequency
}

// GetFrequencyOk returns a tuple with the Frequency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditBackupScheduleParams) GetFrequencyOk() (*int64, bool) {
	if o == nil || o.Frequency == nil {
		return nil, false
	}
	return o.Frequency, true
}

// HasFrequency returns a boolean if a field has been set.
func (o *EditBackupScheduleParams) HasFrequency() bool {
	if o != nil && o.Frequency != nil {
		return true
	}

	return false
}

// SetFrequency gets a reference to the given int64 and assigns it to the Frequency field.
func (o *EditBackupScheduleParams) SetFrequency(v int64) {
	o.Frequency = &v
}

// GetFrequencyTimeUnit returns the FrequencyTimeUnit field value if set, zero value otherwise.
func (o *EditBackupScheduleParams) GetFrequencyTimeUnit() string {
	if o == nil || o.FrequencyTimeUnit == nil {
		var ret string
		return ret
	}
	return *o.FrequencyTimeUnit
}

// GetFrequencyTimeUnitOk returns a tuple with the FrequencyTimeUnit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditBackupScheduleParams) GetFrequencyTimeUnitOk() (*string, bool) {
	if o == nil || o.FrequencyTimeUnit == nil {
		return nil, false
	}
	return o.FrequencyTimeUnit, true
}

// HasFrequencyTimeUnit returns a boolean if a field has been set.
func (o *EditBackupScheduleParams) HasFrequencyTimeUnit() bool {
	if o != nil && o.FrequencyTimeUnit != nil {
		return true
	}

	return false
}

// SetFrequencyTimeUnit gets a reference to the given string and assigns it to the FrequencyTimeUnit field.
func (o *EditBackupScheduleParams) SetFrequencyTimeUnit(v string) {
	o.FrequencyTimeUnit = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *EditBackupScheduleParams) GetStatus() string {
	if o == nil || o.Status == nil {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditBackupScheduleParams) GetStatusOk() (*string, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *EditBackupScheduleParams) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *EditBackupScheduleParams) SetStatus(v string) {
	o.Status = &v
}

func (o EditBackupScheduleParams) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.CronExpression != nil {
		toSerialize["cronExpression"] = o.CronExpression
	}
	if o.Frequency != nil {
		toSerialize["frequency"] = o.Frequency
	}
	if o.FrequencyTimeUnit != nil {
		toSerialize["frequencyTimeUnit"] = o.FrequencyTimeUnit
	}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	return json.Marshal(toSerialize)
}

type NullableEditBackupScheduleParams struct {
	value *EditBackupScheduleParams
	isSet bool
}

func (v NullableEditBackupScheduleParams) Get() *EditBackupScheduleParams {
	return v.value
}

func (v *NullableEditBackupScheduleParams) Set(val *EditBackupScheduleParams) {
	v.value = val
	v.isSet = true
}

func (v NullableEditBackupScheduleParams) IsSet() bool {
	return v.isSet
}

func (v *NullableEditBackupScheduleParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEditBackupScheduleParams(val *EditBackupScheduleParams) *NullableEditBackupScheduleParams {
	return &NullableEditBackupScheduleParams{value: val, isSet: true}
}

func (v NullableEditBackupScheduleParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEditBackupScheduleParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


