/*
YugabyteDB Anywhere APIs

ALPHA - NOT FOR EXTERNAL USE

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ywclient

import (
	"encoding/json"
)

// checks if the AlertTemplateVariablesFormData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AlertTemplateVariablesFormData{}

// AlertTemplateVariablesFormData struct for AlertTemplateVariablesFormData
type AlertTemplateVariablesFormData struct {
	Variables []AlertTemplateVariable `json:"variables"`
}

type _AlertTemplateVariablesFormData AlertTemplateVariablesFormData

// NewAlertTemplateVariablesFormData instantiates a new AlertTemplateVariablesFormData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAlertTemplateVariablesFormData(variables []AlertTemplateVariable) *AlertTemplateVariablesFormData {
	this := AlertTemplateVariablesFormData{}
	this.Variables = variables
	return &this
}

// NewAlertTemplateVariablesFormDataWithDefaults instantiates a new AlertTemplateVariablesFormData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAlertTemplateVariablesFormDataWithDefaults() *AlertTemplateVariablesFormData {
	this := AlertTemplateVariablesFormData{}
	return &this
}

// GetVariables returns the Variables field value
func (o *AlertTemplateVariablesFormData) GetVariables() []AlertTemplateVariable {
	if o == nil {
		var ret []AlertTemplateVariable
		return ret
	}

	return o.Variables
}

// GetVariablesOk returns a tuple with the Variables field value
// and a boolean to check if the value has been set.
func (o *AlertTemplateVariablesFormData) GetVariablesOk() ([]AlertTemplateVariable, bool) {
	if o == nil {
		return nil, false
	}
	return o.Variables, true
}

// SetVariables sets field value
func (o *AlertTemplateVariablesFormData) SetVariables(v []AlertTemplateVariable) {
	o.Variables = v
}

func (o AlertTemplateVariablesFormData) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AlertTemplateVariablesFormData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["variables"] = o.Variables
	return toSerialize, nil
}

type NullableAlertTemplateVariablesFormData struct {
	value *AlertTemplateVariablesFormData
	isSet bool
}

func (v NullableAlertTemplateVariablesFormData) Get() *AlertTemplateVariablesFormData {
	return v.value
}

func (v *NullableAlertTemplateVariablesFormData) Set(val *AlertTemplateVariablesFormData) {
	v.value = val
	v.isSet = true
}

func (v NullableAlertTemplateVariablesFormData) IsSet() bool {
	return v.isSet
}

func (v *NullableAlertTemplateVariablesFormData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAlertTemplateVariablesFormData(val *AlertTemplateVariablesFormData) *NullableAlertTemplateVariablesFormData {
	return &NullableAlertTemplateVariablesFormData{value: val, isSet: true}
}

func (v NullableAlertTemplateVariablesFormData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAlertTemplateVariablesFormData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
