/*
 * YugabyteDB Anywhere APIs
 *
 * ALPHA - NOT FOR EXTERNAL USE
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ywclient

import (
	"encoding/json"
)

// AlertChannelTemplatesExtWithDefaultValues struct for AlertChannelTemplatesExtWithDefaultValues
type AlertChannelTemplatesExtWithDefaultValues struct {
	// Customer UUID
	CustomerUUID string `json:"customerUUID"`
	// Default text template
	DefaultTextTemplate *string `json:"defaultTextTemplate,omitempty"`
	// Default title template
	DefaultTitleTemplate *string `json:"defaultTitleTemplate,omitempty"`
	// Notification text template
	TextTemplate string `json:"textTemplate"`
	// Notification title template
	TitleTemplate *string `json:"titleTemplate,omitempty"`
	// Channel type
	Type string `json:"type"`
}

// NewAlertChannelTemplatesExtWithDefaultValues instantiates a new AlertChannelTemplatesExtWithDefaultValues object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAlertChannelTemplatesExtWithDefaultValues(customerUUID string, textTemplate string, type_ string) *AlertChannelTemplatesExtWithDefaultValues {
	this := AlertChannelTemplatesExtWithDefaultValues{}
	this.CustomerUUID = customerUUID
	this.TextTemplate = textTemplate
	this.Type = type_
	return &this
}

// NewAlertChannelTemplatesExtWithDefaultValuesWithDefaults instantiates a new AlertChannelTemplatesExtWithDefaultValues object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAlertChannelTemplatesExtWithDefaultValuesWithDefaults() *AlertChannelTemplatesExtWithDefaultValues {
	this := AlertChannelTemplatesExtWithDefaultValues{}
	return &this
}

// GetCustomerUUID returns the CustomerUUID field value
func (o *AlertChannelTemplatesExtWithDefaultValues) GetCustomerUUID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CustomerUUID
}

// GetCustomerUUIDOk returns a tuple with the CustomerUUID field value
// and a boolean to check if the value has been set.
func (o *AlertChannelTemplatesExtWithDefaultValues) GetCustomerUUIDOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.CustomerUUID, true
}

// SetCustomerUUID sets field value
func (o *AlertChannelTemplatesExtWithDefaultValues) SetCustomerUUID(v string) {
	o.CustomerUUID = v
}

// GetDefaultTextTemplate returns the DefaultTextTemplate field value if set, zero value otherwise.
func (o *AlertChannelTemplatesExtWithDefaultValues) GetDefaultTextTemplate() string {
	if o == nil || o.DefaultTextTemplate == nil {
		var ret string
		return ret
	}
	return *o.DefaultTextTemplate
}

// GetDefaultTextTemplateOk returns a tuple with the DefaultTextTemplate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlertChannelTemplatesExtWithDefaultValues) GetDefaultTextTemplateOk() (*string, bool) {
	if o == nil || o.DefaultTextTemplate == nil {
		return nil, false
	}
	return o.DefaultTextTemplate, true
}

// HasDefaultTextTemplate returns a boolean if a field has been set.
func (o *AlertChannelTemplatesExtWithDefaultValues) HasDefaultTextTemplate() bool {
	if o != nil && o.DefaultTextTemplate != nil {
		return true
	}

	return false
}

// SetDefaultTextTemplate gets a reference to the given string and assigns it to the DefaultTextTemplate field.
func (o *AlertChannelTemplatesExtWithDefaultValues) SetDefaultTextTemplate(v string) {
	o.DefaultTextTemplate = &v
}

// GetDefaultTitleTemplate returns the DefaultTitleTemplate field value if set, zero value otherwise.
func (o *AlertChannelTemplatesExtWithDefaultValues) GetDefaultTitleTemplate() string {
	if o == nil || o.DefaultTitleTemplate == nil {
		var ret string
		return ret
	}
	return *o.DefaultTitleTemplate
}

// GetDefaultTitleTemplateOk returns a tuple with the DefaultTitleTemplate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlertChannelTemplatesExtWithDefaultValues) GetDefaultTitleTemplateOk() (*string, bool) {
	if o == nil || o.DefaultTitleTemplate == nil {
		return nil, false
	}
	return o.DefaultTitleTemplate, true
}

// HasDefaultTitleTemplate returns a boolean if a field has been set.
func (o *AlertChannelTemplatesExtWithDefaultValues) HasDefaultTitleTemplate() bool {
	if o != nil && o.DefaultTitleTemplate != nil {
		return true
	}

	return false
}

// SetDefaultTitleTemplate gets a reference to the given string and assigns it to the DefaultTitleTemplate field.
func (o *AlertChannelTemplatesExtWithDefaultValues) SetDefaultTitleTemplate(v string) {
	o.DefaultTitleTemplate = &v
}

// GetTextTemplate returns the TextTemplate field value
func (o *AlertChannelTemplatesExtWithDefaultValues) GetTextTemplate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TextTemplate
}

// GetTextTemplateOk returns a tuple with the TextTemplate field value
// and a boolean to check if the value has been set.
func (o *AlertChannelTemplatesExtWithDefaultValues) GetTextTemplateOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.TextTemplate, true
}

// SetTextTemplate sets field value
func (o *AlertChannelTemplatesExtWithDefaultValues) SetTextTemplate(v string) {
	o.TextTemplate = v
}

// GetTitleTemplate returns the TitleTemplate field value if set, zero value otherwise.
func (o *AlertChannelTemplatesExtWithDefaultValues) GetTitleTemplate() string {
	if o == nil || o.TitleTemplate == nil {
		var ret string
		return ret
	}
	return *o.TitleTemplate
}

// GetTitleTemplateOk returns a tuple with the TitleTemplate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlertChannelTemplatesExtWithDefaultValues) GetTitleTemplateOk() (*string, bool) {
	if o == nil || o.TitleTemplate == nil {
		return nil, false
	}
	return o.TitleTemplate, true
}

// HasTitleTemplate returns a boolean if a field has been set.
func (o *AlertChannelTemplatesExtWithDefaultValues) HasTitleTemplate() bool {
	if o != nil && o.TitleTemplate != nil {
		return true
	}

	return false
}

// SetTitleTemplate gets a reference to the given string and assigns it to the TitleTemplate field.
func (o *AlertChannelTemplatesExtWithDefaultValues) SetTitleTemplate(v string) {
	o.TitleTemplate = &v
}

// GetType returns the Type field value
func (o *AlertChannelTemplatesExtWithDefaultValues) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *AlertChannelTemplatesExtWithDefaultValues) GetTypeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *AlertChannelTemplatesExtWithDefaultValues) SetType(v string) {
	o.Type = v
}

func (o AlertChannelTemplatesExtWithDefaultValues) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["customerUUID"] = o.CustomerUUID
	}
	if o.DefaultTextTemplate != nil {
		toSerialize["defaultTextTemplate"] = o.DefaultTextTemplate
	}
	if o.DefaultTitleTemplate != nil {
		toSerialize["defaultTitleTemplate"] = o.DefaultTitleTemplate
	}
	if true {
		toSerialize["textTemplate"] = o.TextTemplate
	}
	if o.TitleTemplate != nil {
		toSerialize["titleTemplate"] = o.TitleTemplate
	}
	if true {
		toSerialize["type"] = o.Type
	}
	return json.Marshal(toSerialize)
}

type NullableAlertChannelTemplatesExtWithDefaultValues struct {
	value *AlertChannelTemplatesExtWithDefaultValues
	isSet bool
}

func (v NullableAlertChannelTemplatesExtWithDefaultValues) Get() *AlertChannelTemplatesExtWithDefaultValues {
	return v.value
}

func (v *NullableAlertChannelTemplatesExtWithDefaultValues) Set(val *AlertChannelTemplatesExtWithDefaultValues) {
	v.value = val
	v.isSet = true
}

func (v NullableAlertChannelTemplatesExtWithDefaultValues) IsSet() bool {
	return v.isSet
}

func (v *NullableAlertChannelTemplatesExtWithDefaultValues) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAlertChannelTemplatesExtWithDefaultValues(val *AlertChannelTemplatesExtWithDefaultValues) *NullableAlertChannelTemplatesExtWithDefaultValues {
	return &NullableAlertChannelTemplatesExtWithDefaultValues{value: val, isSet: true}
}

func (v NullableAlertChannelTemplatesExtWithDefaultValues) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAlertChannelTemplatesExtWithDefaultValues) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


