/*
YugabyteDB Anywhere V2 APIs

An improved set of APIs for managing YugabyteDB Anywhere

API version: v2
Contact: support@yugabyte.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v2

import (
	"encoding/json"
)

// checks if the PlacementRegion type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PlacementRegion{}

// PlacementRegion YBA Placement Region. Part of PlacementCloud.
type PlacementRegion struct {
	// The region provider id.
	Uuid string `json:"uuid"`
	// The actual provider given region code.
	Code string `json:"code"`
	// The region name.
	Name *string `json:"name,omitempty"`
	// The list of AZs inside this region into which we want to place data.
	AzList []PlacementAZ `json:"az_list"`
	// The Load Balancer FQDN.
	LbFqdn *string `json:"lb_fqdn,omitempty"`
}

type _PlacementRegion PlacementRegion

// NewPlacementRegion instantiates a new PlacementRegion object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlacementRegion(uuid string, code string, azList []PlacementAZ) *PlacementRegion {
	this := PlacementRegion{}
	this.Uuid = uuid
	this.Code = code
	this.AzList = azList
	return &this
}

// NewPlacementRegionWithDefaults instantiates a new PlacementRegion object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlacementRegionWithDefaults() *PlacementRegion {
	this := PlacementRegion{}
	return &this
}

// GetUuid returns the Uuid field value
func (o *PlacementRegion) GetUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value
// and a boolean to check if the value has been set.
func (o *PlacementRegion) GetUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uuid, true
}

// SetUuid sets field value
func (o *PlacementRegion) SetUuid(v string) {
	o.Uuid = v
}

// GetCode returns the Code field value
func (o *PlacementRegion) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *PlacementRegion) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *PlacementRegion) SetCode(v string) {
	o.Code = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *PlacementRegion) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlacementRegion) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *PlacementRegion) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *PlacementRegion) SetName(v string) {
	o.Name = &v
}

// GetAzList returns the AzList field value
func (o *PlacementRegion) GetAzList() []PlacementAZ {
	if o == nil {
		var ret []PlacementAZ
		return ret
	}

	return o.AzList
}

// GetAzListOk returns a tuple with the AzList field value
// and a boolean to check if the value has been set.
func (o *PlacementRegion) GetAzListOk() ([]PlacementAZ, bool) {
	if o == nil {
		return nil, false
	}
	return o.AzList, true
}

// SetAzList sets field value
func (o *PlacementRegion) SetAzList(v []PlacementAZ) {
	o.AzList = v
}

// GetLbFqdn returns the LbFqdn field value if set, zero value otherwise.
func (o *PlacementRegion) GetLbFqdn() string {
	if o == nil || IsNil(o.LbFqdn) {
		var ret string
		return ret
	}
	return *o.LbFqdn
}

// GetLbFqdnOk returns a tuple with the LbFqdn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlacementRegion) GetLbFqdnOk() (*string, bool) {
	if o == nil || IsNil(o.LbFqdn) {
		return nil, false
	}
	return o.LbFqdn, true
}

// HasLbFqdn returns a boolean if a field has been set.
func (o *PlacementRegion) HasLbFqdn() bool {
	if o != nil && !IsNil(o.LbFqdn) {
		return true
	}

	return false
}

// SetLbFqdn gets a reference to the given string and assigns it to the LbFqdn field.
func (o *PlacementRegion) SetLbFqdn(v string) {
	o.LbFqdn = &v
}

func (o PlacementRegion) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PlacementRegion) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["uuid"] = o.Uuid
	toSerialize["code"] = o.Code
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	toSerialize["az_list"] = o.AzList
	if !IsNil(o.LbFqdn) {
		toSerialize["lb_fqdn"] = o.LbFqdn
	}
	return toSerialize, nil
}

type NullablePlacementRegion struct {
	value *PlacementRegion
	isSet bool
}

func (v NullablePlacementRegion) Get() *PlacementRegion {
	return v.value
}

func (v *NullablePlacementRegion) Set(val *PlacementRegion) {
	v.value = val
	v.isSet = true
}

func (v NullablePlacementRegion) IsSet() bool {
	return v.isSet
}

func (v *NullablePlacementRegion) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlacementRegion(val *PlacementRegion) *NullablePlacementRegion {
	return &NullablePlacementRegion{value: val, isSet: true}
}

func (v NullablePlacementRegion) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlacementRegion) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
