/*
 * YugabyteDB Anywhere V2 APIs
 *
 * An improved set of APIs for managing YugabyteDB Anywhere
 *
 * API version: v2
 * Contact: support@yugabyte.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v2

import (
	"encoding/json"
)

// ClusterProviderSpec struct for ClusterProviderSpec
type ClusterProviderSpec struct {
	// Cloud provider UUID
	Provider string `json:"provider"`
	// The list of regions in the cloud provider to place data replicas
	RegionList *[]string `json:"region_list,omitempty"`
	// The region to nominate as the preferred region in a geo-partitioned multi-region cluster
	PreferredRegion *string `json:"preferred_region,omitempty"`
	// One of the SSH access keys defined in Cloud Provider to be configured on nodes VMs
	AccessKeyCode string `json:"access_key_code"`
	// Image bundle UUID to use for node VM image. Refers to one of the image bundles defined in the cloud provider.
	ImageBundleUuid *string `json:"image_bundle_uuid,omitempty"`
}

// NewClusterProviderSpec instantiates a new ClusterProviderSpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClusterProviderSpec(provider string, accessKeyCode string) *ClusterProviderSpec {
	this := ClusterProviderSpec{}
	this.Provider = provider
	this.AccessKeyCode = accessKeyCode
	return &this
}

// NewClusterProviderSpecWithDefaults instantiates a new ClusterProviderSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClusterProviderSpecWithDefaults() *ClusterProviderSpec {
	this := ClusterProviderSpec{}
	return &this
}

// GetProvider returns the Provider field value
func (o *ClusterProviderSpec) GetProvider() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Provider
}

// GetProviderOk returns a tuple with the Provider field value
// and a boolean to check if the value has been set.
func (o *ClusterProviderSpec) GetProviderOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Provider, true
}

// SetProvider sets field value
func (o *ClusterProviderSpec) SetProvider(v string) {
	o.Provider = v
}

// GetRegionList returns the RegionList field value if set, zero value otherwise.
func (o *ClusterProviderSpec) GetRegionList() []string {
	if o == nil || o.RegionList == nil {
		var ret []string
		return ret
	}
	return *o.RegionList
}

// GetRegionListOk returns a tuple with the RegionList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterProviderSpec) GetRegionListOk() (*[]string, bool) {
	if o == nil || o.RegionList == nil {
		return nil, false
	}
	return o.RegionList, true
}

// HasRegionList returns a boolean if a field has been set.
func (o *ClusterProviderSpec) HasRegionList() bool {
	if o != nil && o.RegionList != nil {
		return true
	}

	return false
}

// SetRegionList gets a reference to the given []string and assigns it to the RegionList field.
func (o *ClusterProviderSpec) SetRegionList(v []string) {
	o.RegionList = &v
}

// GetPreferredRegion returns the PreferredRegion field value if set, zero value otherwise.
func (o *ClusterProviderSpec) GetPreferredRegion() string {
	if o == nil || o.PreferredRegion == nil {
		var ret string
		return ret
	}
	return *o.PreferredRegion
}

// GetPreferredRegionOk returns a tuple with the PreferredRegion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterProviderSpec) GetPreferredRegionOk() (*string, bool) {
	if o == nil || o.PreferredRegion == nil {
		return nil, false
	}
	return o.PreferredRegion, true
}

// HasPreferredRegion returns a boolean if a field has been set.
func (o *ClusterProviderSpec) HasPreferredRegion() bool {
	if o != nil && o.PreferredRegion != nil {
		return true
	}

	return false
}

// SetPreferredRegion gets a reference to the given string and assigns it to the PreferredRegion field.
func (o *ClusterProviderSpec) SetPreferredRegion(v string) {
	o.PreferredRegion = &v
}

// GetAccessKeyCode returns the AccessKeyCode field value
func (o *ClusterProviderSpec) GetAccessKeyCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccessKeyCode
}

// GetAccessKeyCodeOk returns a tuple with the AccessKeyCode field value
// and a boolean to check if the value has been set.
func (o *ClusterProviderSpec) GetAccessKeyCodeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.AccessKeyCode, true
}

// SetAccessKeyCode sets field value
func (o *ClusterProviderSpec) SetAccessKeyCode(v string) {
	o.AccessKeyCode = v
}

// GetImageBundleUuid returns the ImageBundleUuid field value if set, zero value otherwise.
func (o *ClusterProviderSpec) GetImageBundleUuid() string {
	if o == nil || o.ImageBundleUuid == nil {
		var ret string
		return ret
	}
	return *o.ImageBundleUuid
}

// GetImageBundleUuidOk returns a tuple with the ImageBundleUuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterProviderSpec) GetImageBundleUuidOk() (*string, bool) {
	if o == nil || o.ImageBundleUuid == nil {
		return nil, false
	}
	return o.ImageBundleUuid, true
}

// HasImageBundleUuid returns a boolean if a field has been set.
func (o *ClusterProviderSpec) HasImageBundleUuid() bool {
	if o != nil && o.ImageBundleUuid != nil {
		return true
	}

	return false
}

// SetImageBundleUuid gets a reference to the given string and assigns it to the ImageBundleUuid field.
func (o *ClusterProviderSpec) SetImageBundleUuid(v string) {
	o.ImageBundleUuid = &v
}

func (o ClusterProviderSpec) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["provider"] = o.Provider
	}
	if o.RegionList != nil {
		toSerialize["region_list"] = o.RegionList
	}
	if o.PreferredRegion != nil {
		toSerialize["preferred_region"] = o.PreferredRegion
	}
	if true {
		toSerialize["access_key_code"] = o.AccessKeyCode
	}
	if o.ImageBundleUuid != nil {
		toSerialize["image_bundle_uuid"] = o.ImageBundleUuid
	}
	return json.Marshal(toSerialize)
}

type NullableClusterProviderSpec struct {
	value *ClusterProviderSpec
	isSet bool
}

func (v NullableClusterProviderSpec) Get() *ClusterProviderSpec {
	return v.value
}

func (v *NullableClusterProviderSpec) Set(val *ClusterProviderSpec) {
	v.value = val
	v.isSet = true
}

func (v NullableClusterProviderSpec) IsSet() bool {
	return v.isSet
}

func (v *NullableClusterProviderSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClusterProviderSpec(val *ClusterProviderSpec) *NullableClusterProviderSpec {
	return &NullableClusterProviderSpec{value: val, isSet: true}
}

func (v NullableClusterProviderSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClusterProviderSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


