/*
YugabyteDB Anywhere V2 APIs

An improved set of APIs for managing YugabyteDB Anywhere

API version: v2
Contact: support@yugabyte.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v2

import (
	"encoding/json"
)

// checks if the FilesComponentSpec type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FilesComponentSpec{}

// FilesComponentSpec Spec driving the generic node-level FilesComponent.
type FilesComponentSpec struct {
	// Logical component name; used as a label/sub-directory. Must be a single file name of up to 128 characters from [A-Za-z0-9._-].
	ComponentName *string `json:"component_name,omitempty"`
	// Path on the YBA host to the script file to execute on the node. Must resolve to one of the shipped support bundle scripts, node_utils.sh or yba_utils.sh, under the platform devops directory. A relative path is resolved against that directory. Any other path is rejected.
	ScriptPath *string `json:"script_path,omitempty"`
	// Arguments appended after the script (entrypoint + flags).
	Params []string `json:"params,omitempty"`
	// Path on the node where the script writes the tar. May contain ${nodeName}. Must be an absolute path without '..', built only from letters, digits, '.', '_', '-', '/' and the ${nodeName} / ${bundleUuid} tokens.
	RemoteTarPath *string `json:"remote_tar_path,omitempty"`
	// Linux user to run the script as on the node. Only yugabyte is accepted; leave it unset to get the same result. The SystemLogs component is the one exception, as it needs the provider SSH user and sudo to read /var/log.
	LinuxUser *string `json:"linux_user,omitempty"`
	// Script execution timeout in seconds.
	TimeoutSecs *int64 `json:"timeout_secs,omitempty"`
}

// NewFilesComponentSpec instantiates a new FilesComponentSpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFilesComponentSpec() *FilesComponentSpec {
	this := FilesComponentSpec{}
	return &this
}

// NewFilesComponentSpecWithDefaults instantiates a new FilesComponentSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFilesComponentSpecWithDefaults() *FilesComponentSpec {
	this := FilesComponentSpec{}
	return &this
}

// GetComponentName returns the ComponentName field value if set, zero value otherwise.
func (o *FilesComponentSpec) GetComponentName() string {
	if o == nil || IsNil(o.ComponentName) {
		var ret string
		return ret
	}
	return *o.ComponentName
}

// GetComponentNameOk returns a tuple with the ComponentName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FilesComponentSpec) GetComponentNameOk() (*string, bool) {
	if o == nil || IsNil(o.ComponentName) {
		return nil, false
	}
	return o.ComponentName, true
}

// HasComponentName returns a boolean if a field has been set.
func (o *FilesComponentSpec) HasComponentName() bool {
	if o != nil && !IsNil(o.ComponentName) {
		return true
	}

	return false
}

// SetComponentName gets a reference to the given string and assigns it to the ComponentName field.
func (o *FilesComponentSpec) SetComponentName(v string) {
	o.ComponentName = &v
}

// GetScriptPath returns the ScriptPath field value if set, zero value otherwise.
func (o *FilesComponentSpec) GetScriptPath() string {
	if o == nil || IsNil(o.ScriptPath) {
		var ret string
		return ret
	}
	return *o.ScriptPath
}

// GetScriptPathOk returns a tuple with the ScriptPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FilesComponentSpec) GetScriptPathOk() (*string, bool) {
	if o == nil || IsNil(o.ScriptPath) {
		return nil, false
	}
	return o.ScriptPath, true
}

// HasScriptPath returns a boolean if a field has been set.
func (o *FilesComponentSpec) HasScriptPath() bool {
	if o != nil && !IsNil(o.ScriptPath) {
		return true
	}

	return false
}

// SetScriptPath gets a reference to the given string and assigns it to the ScriptPath field.
func (o *FilesComponentSpec) SetScriptPath(v string) {
	o.ScriptPath = &v
}

// GetParams returns the Params field value if set, zero value otherwise.
func (o *FilesComponentSpec) GetParams() []string {
	if o == nil || IsNil(o.Params) {
		var ret []string
		return ret
	}
	return o.Params
}

// GetParamsOk returns a tuple with the Params field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FilesComponentSpec) GetParamsOk() ([]string, bool) {
	if o == nil || IsNil(o.Params) {
		return nil, false
	}
	return o.Params, true
}

// HasParams returns a boolean if a field has been set.
func (o *FilesComponentSpec) HasParams() bool {
	if o != nil && !IsNil(o.Params) {
		return true
	}

	return false
}

// SetParams gets a reference to the given []string and assigns it to the Params field.
func (o *FilesComponentSpec) SetParams(v []string) {
	o.Params = v
}

// GetRemoteTarPath returns the RemoteTarPath field value if set, zero value otherwise.
func (o *FilesComponentSpec) GetRemoteTarPath() string {
	if o == nil || IsNil(o.RemoteTarPath) {
		var ret string
		return ret
	}
	return *o.RemoteTarPath
}

// GetRemoteTarPathOk returns a tuple with the RemoteTarPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FilesComponentSpec) GetRemoteTarPathOk() (*string, bool) {
	if o == nil || IsNil(o.RemoteTarPath) {
		return nil, false
	}
	return o.RemoteTarPath, true
}

// HasRemoteTarPath returns a boolean if a field has been set.
func (o *FilesComponentSpec) HasRemoteTarPath() bool {
	if o != nil && !IsNil(o.RemoteTarPath) {
		return true
	}

	return false
}

// SetRemoteTarPath gets a reference to the given string and assigns it to the RemoteTarPath field.
func (o *FilesComponentSpec) SetRemoteTarPath(v string) {
	o.RemoteTarPath = &v
}

// GetLinuxUser returns the LinuxUser field value if set, zero value otherwise.
func (o *FilesComponentSpec) GetLinuxUser() string {
	if o == nil || IsNil(o.LinuxUser) {
		var ret string
		return ret
	}
	return *o.LinuxUser
}

// GetLinuxUserOk returns a tuple with the LinuxUser field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FilesComponentSpec) GetLinuxUserOk() (*string, bool) {
	if o == nil || IsNil(o.LinuxUser) {
		return nil, false
	}
	return o.LinuxUser, true
}

// HasLinuxUser returns a boolean if a field has been set.
func (o *FilesComponentSpec) HasLinuxUser() bool {
	if o != nil && !IsNil(o.LinuxUser) {
		return true
	}

	return false
}

// SetLinuxUser gets a reference to the given string and assigns it to the LinuxUser field.
func (o *FilesComponentSpec) SetLinuxUser(v string) {
	o.LinuxUser = &v
}

// GetTimeoutSecs returns the TimeoutSecs field value if set, zero value otherwise.
func (o *FilesComponentSpec) GetTimeoutSecs() int64 {
	if o == nil || IsNil(o.TimeoutSecs) {
		var ret int64
		return ret
	}
	return *o.TimeoutSecs
}

// GetTimeoutSecsOk returns a tuple with the TimeoutSecs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FilesComponentSpec) GetTimeoutSecsOk() (*int64, bool) {
	if o == nil || IsNil(o.TimeoutSecs) {
		return nil, false
	}
	return o.TimeoutSecs, true
}

// HasTimeoutSecs returns a boolean if a field has been set.
func (o *FilesComponentSpec) HasTimeoutSecs() bool {
	if o != nil && !IsNil(o.TimeoutSecs) {
		return true
	}

	return false
}

// SetTimeoutSecs gets a reference to the given int64 and assigns it to the TimeoutSecs field.
func (o *FilesComponentSpec) SetTimeoutSecs(v int64) {
	o.TimeoutSecs = &v
}

func (o FilesComponentSpec) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FilesComponentSpec) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ComponentName) {
		toSerialize["component_name"] = o.ComponentName
	}
	if !IsNil(o.ScriptPath) {
		toSerialize["script_path"] = o.ScriptPath
	}
	if !IsNil(o.Params) {
		toSerialize["params"] = o.Params
	}
	if !IsNil(o.RemoteTarPath) {
		toSerialize["remote_tar_path"] = o.RemoteTarPath
	}
	if !IsNil(o.LinuxUser) {
		toSerialize["linux_user"] = o.LinuxUser
	}
	if !IsNil(o.TimeoutSecs) {
		toSerialize["timeout_secs"] = o.TimeoutSecs
	}
	return toSerialize, nil
}

type NullableFilesComponentSpec struct {
	value *FilesComponentSpec
	isSet bool
}

func (v NullableFilesComponentSpec) Get() *FilesComponentSpec {
	return v.value
}

func (v *NullableFilesComponentSpec) Set(val *FilesComponentSpec) {
	v.value = val
	v.isSet = true
}

func (v NullableFilesComponentSpec) IsSet() bool {
	return v.isSet
}

func (v *NullableFilesComponentSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFilesComponentSpec(val *FilesComponentSpec) *NullableFilesComponentSpec {
	return &NullableFilesComponentSpec{value: val, isSet: true}
}

func (v NullableFilesComponentSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFilesComponentSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
