/*
YugabyteDB Anywhere V2 APIs

An improved set of APIs for managing YugabyteDB Anywhere

API version: v2
Contact: support@yugabyte.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v2

import (
	"encoding/json"
)

// checks if the DrConfigTableDetailPagedQuerySpec type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DrConfigTableDetailPagedQuerySpec{}

// DrConfigTableDetailPagedQuerySpec Paged list of table replication details for a DR config. Rows are ordered by table ID. The order is ascending by default.
type DrConfigTableDetailPagedQuerySpec struct {
	PaginationSpec
}

// NewDrConfigTableDetailPagedQuerySpec instantiates a new DrConfigTableDetailPagedQuerySpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDrConfigTableDetailPagedQuerySpec() *DrConfigTableDetailPagedQuerySpec {
	this := DrConfigTableDetailPagedQuerySpec{}
	var offset int32 = 0
	this.Offset = &offset
	var limit int32 = 10
	this.Limit = &limit
	return &this
}

// NewDrConfigTableDetailPagedQuerySpecWithDefaults instantiates a new DrConfigTableDetailPagedQuerySpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDrConfigTableDetailPagedQuerySpecWithDefaults() *DrConfigTableDetailPagedQuerySpec {
	this := DrConfigTableDetailPagedQuerySpec{}
	return &this
}

func (o DrConfigTableDetailPagedQuerySpec) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DrConfigTableDetailPagedQuerySpec) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	return toSerialize, nil
}

type NullableDrConfigTableDetailPagedQuerySpec struct {
	value *DrConfigTableDetailPagedQuerySpec
	isSet bool
}

func (v NullableDrConfigTableDetailPagedQuerySpec) Get() *DrConfigTableDetailPagedQuerySpec {
	return v.value
}

func (v *NullableDrConfigTableDetailPagedQuerySpec) Set(val *DrConfigTableDetailPagedQuerySpec) {
	v.value = val
	v.isSet = true
}

func (v NullableDrConfigTableDetailPagedQuerySpec) IsSet() bool {
	return v.isSet
}

func (v *NullableDrConfigTableDetailPagedQuerySpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDrConfigTableDetailPagedQuerySpec(val *DrConfigTableDetailPagedQuerySpec) *NullableDrConfigTableDetailPagedQuerySpec {
	return &NullableDrConfigTableDetailPagedQuerySpec{value: val, isSet: true}
}

func (v NullableDrConfigTableDetailPagedQuerySpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDrConfigTableDetailPagedQuerySpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
