/*
 * YugabyteDB Anywhere V2 APIs
 *
 * An improved set of APIs for managing YugabyteDB Anywhere
 *
 * API version: v2
 * Contact: support@yugabyte.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v2

import (
	"encoding/json"
)

// YsqlSpec struct for YsqlSpec
type YsqlSpec struct {
	// Whether to enable YSQL API on this Universe
	Enable *bool `json:"enable,omitempty"`
	// Whether to enable authentication to access YSQL on this Universe
	EnableAuth *bool `json:"enable_auth,omitempty"`
}

// NewYsqlSpec instantiates a new YsqlSpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewYsqlSpec() *YsqlSpec {
	this := YsqlSpec{}
	return &this
}

// NewYsqlSpecWithDefaults instantiates a new YsqlSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewYsqlSpecWithDefaults() *YsqlSpec {
	this := YsqlSpec{}
	return &this
}

// GetEnable returns the Enable field value if set, zero value otherwise.
func (o *YsqlSpec) GetEnable() bool {
	if o == nil || o.Enable == nil {
		var ret bool
		return ret
	}
	return *o.Enable
}

// GetEnableOk returns a tuple with the Enable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *YsqlSpec) GetEnableOk() (*bool, bool) {
	if o == nil || o.Enable == nil {
		return nil, false
	}
	return o.Enable, true
}

// HasEnable returns a boolean if a field has been set.
func (o *YsqlSpec) HasEnable() bool {
	if o != nil && o.Enable != nil {
		return true
	}

	return false
}

// SetEnable gets a reference to the given bool and assigns it to the Enable field.
func (o *YsqlSpec) SetEnable(v bool) {
	o.Enable = &v
}

// GetEnableAuth returns the EnableAuth field value if set, zero value otherwise.
func (o *YsqlSpec) GetEnableAuth() bool {
	if o == nil || o.EnableAuth == nil {
		var ret bool
		return ret
	}
	return *o.EnableAuth
}

// GetEnableAuthOk returns a tuple with the EnableAuth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *YsqlSpec) GetEnableAuthOk() (*bool, bool) {
	if o == nil || o.EnableAuth == nil {
		return nil, false
	}
	return o.EnableAuth, true
}

// HasEnableAuth returns a boolean if a field has been set.
func (o *YsqlSpec) HasEnableAuth() bool {
	if o != nil && o.EnableAuth != nil {
		return true
	}

	return false
}

// SetEnableAuth gets a reference to the given bool and assigns it to the EnableAuth field.
func (o *YsqlSpec) SetEnableAuth(v bool) {
	o.EnableAuth = &v
}

func (o YsqlSpec) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Enable != nil {
		toSerialize["enable"] = o.Enable
	}
	if o.EnableAuth != nil {
		toSerialize["enable_auth"] = o.EnableAuth
	}
	return json.Marshal(toSerialize)
}

type NullableYsqlSpec struct {
	value *YsqlSpec
	isSet bool
}

func (v NullableYsqlSpec) Get() *YsqlSpec {
	return v.value
}

func (v *NullableYsqlSpec) Set(val *YsqlSpec) {
	v.value = val
	v.isSet = true
}

func (v NullableYsqlSpec) IsSet() bool {
	return v.isSet
}

func (v *NullableYsqlSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableYsqlSpec(val *YsqlSpec) *NullableYsqlSpec {
	return &NullableYsqlSpec{value: val, isSet: true}
}

func (v NullableYsqlSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableYsqlSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


