/*
YugabyteDB Anywhere V2 APIs

An improved set of APIs for managing YugabyteDB Anywhere

API version: v2
Contact: support@yugabyte.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v2

import (
	"encoding/json"
)

// checks if the ImageBundleDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ImageBundleDetails{}

// ImageBundleDetails Image bundle details (same fields as V1 ImageBundleDetails JSON).
type ImageBundleDetails struct {
	// Default YugabyteDB machine image identifier for this bundle.
	GlobalYbImage *string `json:"global_yb_image,omitempty"`
	// CPU architecture this bundle applies to.
	Arch *string `json:"arch,omitempty"`
	// Per-region YugabyteDB image identifiers keyed by region code.
	Regions *map[string]ImageBundleRegionInfo `json:"regions,omitempty"`
	// SSH username for nodes provisioned from this bundle.
	SshUser *string `json:"ssh_user,omitempty"`
	// SSH port for nodes provisioned from this bundle.
	SshPort *int32 `json:"ssh_port,omitempty"`
	// Whether to require AWS IMDSv2 on supported clouds.
	UseImdsv2 *bool `json:"use_imdsv2,omitempty"`
}

// NewImageBundleDetails instantiates a new ImageBundleDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewImageBundleDetails() *ImageBundleDetails {
	this := ImageBundleDetails{}
	return &this
}

// NewImageBundleDetailsWithDefaults instantiates a new ImageBundleDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewImageBundleDetailsWithDefaults() *ImageBundleDetails {
	this := ImageBundleDetails{}
	return &this
}

// GetGlobalYbImage returns the GlobalYbImage field value if set, zero value otherwise.
func (o *ImageBundleDetails) GetGlobalYbImage() string {
	if o == nil || IsNil(o.GlobalYbImage) {
		var ret string
		return ret
	}
	return *o.GlobalYbImage
}

// GetGlobalYbImageOk returns a tuple with the GlobalYbImage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImageBundleDetails) GetGlobalYbImageOk() (*string, bool) {
	if o == nil || IsNil(o.GlobalYbImage) {
		return nil, false
	}
	return o.GlobalYbImage, true
}

// HasGlobalYbImage returns a boolean if a field has been set.
func (o *ImageBundleDetails) HasGlobalYbImage() bool {
	if o != nil && !IsNil(o.GlobalYbImage) {
		return true
	}

	return false
}

// SetGlobalYbImage gets a reference to the given string and assigns it to the GlobalYbImage field.
func (o *ImageBundleDetails) SetGlobalYbImage(v string) {
	o.GlobalYbImage = &v
}

// GetArch returns the Arch field value if set, zero value otherwise.
func (o *ImageBundleDetails) GetArch() string {
	if o == nil || IsNil(o.Arch) {
		var ret string
		return ret
	}
	return *o.Arch
}

// GetArchOk returns a tuple with the Arch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImageBundleDetails) GetArchOk() (*string, bool) {
	if o == nil || IsNil(o.Arch) {
		return nil, false
	}
	return o.Arch, true
}

// HasArch returns a boolean if a field has been set.
func (o *ImageBundleDetails) HasArch() bool {
	if o != nil && !IsNil(o.Arch) {
		return true
	}

	return false
}

// SetArch gets a reference to the given string and assigns it to the Arch field.
func (o *ImageBundleDetails) SetArch(v string) {
	o.Arch = &v
}

// GetRegions returns the Regions field value if set, zero value otherwise.
func (o *ImageBundleDetails) GetRegions() map[string]ImageBundleRegionInfo {
	if o == nil || IsNil(o.Regions) {
		var ret map[string]ImageBundleRegionInfo
		return ret
	}
	return *o.Regions
}

// GetRegionsOk returns a tuple with the Regions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImageBundleDetails) GetRegionsOk() (*map[string]ImageBundleRegionInfo, bool) {
	if o == nil || IsNil(o.Regions) {
		return nil, false
	}
	return o.Regions, true
}

// HasRegions returns a boolean if a field has been set.
func (o *ImageBundleDetails) HasRegions() bool {
	if o != nil && !IsNil(o.Regions) {
		return true
	}

	return false
}

// SetRegions gets a reference to the given map[string]ImageBundleRegionInfo and assigns it to the Regions field.
func (o *ImageBundleDetails) SetRegions(v map[string]ImageBundleRegionInfo) {
	o.Regions = &v
}

// GetSshUser returns the SshUser field value if set, zero value otherwise.
func (o *ImageBundleDetails) GetSshUser() string {
	if o == nil || IsNil(o.SshUser) {
		var ret string
		return ret
	}
	return *o.SshUser
}

// GetSshUserOk returns a tuple with the SshUser field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImageBundleDetails) GetSshUserOk() (*string, bool) {
	if o == nil || IsNil(o.SshUser) {
		return nil, false
	}
	return o.SshUser, true
}

// HasSshUser returns a boolean if a field has been set.
func (o *ImageBundleDetails) HasSshUser() bool {
	if o != nil && !IsNil(o.SshUser) {
		return true
	}

	return false
}

// SetSshUser gets a reference to the given string and assigns it to the SshUser field.
func (o *ImageBundleDetails) SetSshUser(v string) {
	o.SshUser = &v
}

// GetSshPort returns the SshPort field value if set, zero value otherwise.
func (o *ImageBundleDetails) GetSshPort() int32 {
	if o == nil || IsNil(o.SshPort) {
		var ret int32
		return ret
	}
	return *o.SshPort
}

// GetSshPortOk returns a tuple with the SshPort field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImageBundleDetails) GetSshPortOk() (*int32, bool) {
	if o == nil || IsNil(o.SshPort) {
		return nil, false
	}
	return o.SshPort, true
}

// HasSshPort returns a boolean if a field has been set.
func (o *ImageBundleDetails) HasSshPort() bool {
	if o != nil && !IsNil(o.SshPort) {
		return true
	}

	return false
}

// SetSshPort gets a reference to the given int32 and assigns it to the SshPort field.
func (o *ImageBundleDetails) SetSshPort(v int32) {
	o.SshPort = &v
}

// GetUseImdsv2 returns the UseImdsv2 field value if set, zero value otherwise.
func (o *ImageBundleDetails) GetUseImdsv2() bool {
	if o == nil || IsNil(o.UseImdsv2) {
		var ret bool
		return ret
	}
	return *o.UseImdsv2
}

// GetUseImdsv2Ok returns a tuple with the UseImdsv2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImageBundleDetails) GetUseImdsv2Ok() (*bool, bool) {
	if o == nil || IsNil(o.UseImdsv2) {
		return nil, false
	}
	return o.UseImdsv2, true
}

// HasUseImdsv2 returns a boolean if a field has been set.
func (o *ImageBundleDetails) HasUseImdsv2() bool {
	if o != nil && !IsNil(o.UseImdsv2) {
		return true
	}

	return false
}

// SetUseImdsv2 gets a reference to the given bool and assigns it to the UseImdsv2 field.
func (o *ImageBundleDetails) SetUseImdsv2(v bool) {
	o.UseImdsv2 = &v
}

func (o ImageBundleDetails) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ImageBundleDetails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.GlobalYbImage) {
		toSerialize["global_yb_image"] = o.GlobalYbImage
	}
	if !IsNil(o.Arch) {
		toSerialize["arch"] = o.Arch
	}
	if !IsNil(o.Regions) {
		toSerialize["regions"] = o.Regions
	}
	if !IsNil(o.SshUser) {
		toSerialize["ssh_user"] = o.SshUser
	}
	if !IsNil(o.SshPort) {
		toSerialize["ssh_port"] = o.SshPort
	}
	if !IsNil(o.UseImdsv2) {
		toSerialize["use_imdsv2"] = o.UseImdsv2
	}
	return toSerialize, nil
}

type NullableImageBundleDetails struct {
	value *ImageBundleDetails
	isSet bool
}

func (v NullableImageBundleDetails) Get() *ImageBundleDetails {
	return v.value
}

func (v *NullableImageBundleDetails) Set(val *ImageBundleDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableImageBundleDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableImageBundleDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableImageBundleDetails(val *ImageBundleDetails) *NullableImageBundleDetails {
	return &NullableImageBundleDetails{value: val, isSet: true}
}

func (v NullableImageBundleDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableImageBundleDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
