/*
YugabyteDB Anywhere V2 APIs

An improved set of APIs for managing YugabyteDB Anywhere

API version: v2
Contact: support@yugabyte.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v2

import (
	"encoding/json"
)

// checks if the MemoryLimitedExporterConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MemoryLimitedExporterConfig{}

// MemoryLimitedExporterConfig MemoryLimitedExporterConfig Memory limiter tuning shared by exporters that bound collector memory.
type MemoryLimitedExporterConfig struct {
	// Memory limit in MiB for the OpenTelemetry Collector process in the config file.
	MemoryLimitMib *int32 `json:"memory_limit_mib,omitempty"`
	// Check interval in seconds for the MemoryLimiterProcessor.
	MemoryLimitCheckIntervalSeconds *int32 `json:"memory_limit_check_interval_seconds,omitempty"`
}

// NewMemoryLimitedExporterConfig instantiates a new MemoryLimitedExporterConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMemoryLimitedExporterConfig() *MemoryLimitedExporterConfig {
	this := MemoryLimitedExporterConfig{}
	var memoryLimitMib int32 = 2048
	this.MemoryLimitMib = &memoryLimitMib
	var memoryLimitCheckIntervalSeconds int32 = 10
	this.MemoryLimitCheckIntervalSeconds = &memoryLimitCheckIntervalSeconds
	return &this
}

// NewMemoryLimitedExporterConfigWithDefaults instantiates a new MemoryLimitedExporterConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMemoryLimitedExporterConfigWithDefaults() *MemoryLimitedExporterConfig {
	this := MemoryLimitedExporterConfig{}
	var memoryLimitMib int32 = 2048
	this.MemoryLimitMib = &memoryLimitMib
	var memoryLimitCheckIntervalSeconds int32 = 10
	this.MemoryLimitCheckIntervalSeconds = &memoryLimitCheckIntervalSeconds
	return &this
}

// GetMemoryLimitMib returns the MemoryLimitMib field value if set, zero value otherwise.
func (o *MemoryLimitedExporterConfig) GetMemoryLimitMib() int32 {
	if o == nil || IsNil(o.MemoryLimitMib) {
		var ret int32
		return ret
	}
	return *o.MemoryLimitMib
}

// GetMemoryLimitMibOk returns a tuple with the MemoryLimitMib field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MemoryLimitedExporterConfig) GetMemoryLimitMibOk() (*int32, bool) {
	if o == nil || IsNil(o.MemoryLimitMib) {
		return nil, false
	}
	return o.MemoryLimitMib, true
}

// HasMemoryLimitMib returns a boolean if a field has been set.
func (o *MemoryLimitedExporterConfig) HasMemoryLimitMib() bool {
	if o != nil && !IsNil(o.MemoryLimitMib) {
		return true
	}

	return false
}

// SetMemoryLimitMib gets a reference to the given int32 and assigns it to the MemoryLimitMib field.
func (o *MemoryLimitedExporterConfig) SetMemoryLimitMib(v int32) {
	o.MemoryLimitMib = &v
}

// GetMemoryLimitCheckIntervalSeconds returns the MemoryLimitCheckIntervalSeconds field value if set, zero value otherwise.
func (o *MemoryLimitedExporterConfig) GetMemoryLimitCheckIntervalSeconds() int32 {
	if o == nil || IsNil(o.MemoryLimitCheckIntervalSeconds) {
		var ret int32
		return ret
	}
	return *o.MemoryLimitCheckIntervalSeconds
}

// GetMemoryLimitCheckIntervalSecondsOk returns a tuple with the MemoryLimitCheckIntervalSeconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MemoryLimitedExporterConfig) GetMemoryLimitCheckIntervalSecondsOk() (*int32, bool) {
	if o == nil || IsNil(o.MemoryLimitCheckIntervalSeconds) {
		return nil, false
	}
	return o.MemoryLimitCheckIntervalSeconds, true
}

// HasMemoryLimitCheckIntervalSeconds returns a boolean if a field has been set.
func (o *MemoryLimitedExporterConfig) HasMemoryLimitCheckIntervalSeconds() bool {
	if o != nil && !IsNil(o.MemoryLimitCheckIntervalSeconds) {
		return true
	}

	return false
}

// SetMemoryLimitCheckIntervalSeconds gets a reference to the given int32 and assigns it to the MemoryLimitCheckIntervalSeconds field.
func (o *MemoryLimitedExporterConfig) SetMemoryLimitCheckIntervalSeconds(v int32) {
	o.MemoryLimitCheckIntervalSeconds = &v
}

func (o MemoryLimitedExporterConfig) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MemoryLimitedExporterConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MemoryLimitMib) {
		toSerialize["memory_limit_mib"] = o.MemoryLimitMib
	}
	if !IsNil(o.MemoryLimitCheckIntervalSeconds) {
		toSerialize["memory_limit_check_interval_seconds"] = o.MemoryLimitCheckIntervalSeconds
	}
	return toSerialize, nil
}

type NullableMemoryLimitedExporterConfig struct {
	value *MemoryLimitedExporterConfig
	isSet bool
}

func (v NullableMemoryLimitedExporterConfig) Get() *MemoryLimitedExporterConfig {
	return v.value
}

func (v *NullableMemoryLimitedExporterConfig) Set(val *MemoryLimitedExporterConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableMemoryLimitedExporterConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableMemoryLimitedExporterConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMemoryLimitedExporterConfig(val *MemoryLimitedExporterConfig) *NullableMemoryLimitedExporterConfig {
	return &NullableMemoryLimitedExporterConfig{value: val, isSet: true}
}

func (v NullableMemoryLimitedExporterConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMemoryLimitedExporterConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
