/*
YugabyteDB Anywhere V2 APIs

An improved set of APIs for managing YugabyteDB Anywhere

API version: v2
Contact: support@yugabyte.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v2

import (
	"encoding/json"
)

// checks if the YSQLAuditConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &YSQLAuditConfig{}

// YSQLAuditConfig YSQL Audit Logging Configuration. Part of AuditLogConfig.
type YSQLAuditConfig struct {
	// YSQL statement classes
	Classes []string `json:"classes,omitempty"`
	// Enabled
	Enabled bool `json:"enabled"`
	// Log catalog
	LogCatalog bool `json:"log_catalog"`
	// Log client
	LogClient bool `json:"log_client"`
	// Log level
	LogLevel *string `json:"log_level,omitempty"`
	// Log parameter
	LogParameter bool `json:"log_parameter"`
	// Log parameter max size
	LogParameterMaxSize *int32 `json:"log_parameter_max_size,omitempty"`
	// Log relation
	LogRelation bool `json:"log_relation"`
	// Log row
	LogRows bool `json:"log_rows"`
	// Log statement
	LogStatement bool `json:"log_statement"`
	// Log statement once
	LogStatementOnce bool `json:"log_statement_once"`
	// Number of days to keep extracted YSQL audit log archives on the node. 0 or unset disables the dedicated audit-log retention pipeline and keeps the default size-based postgres log purge behavior.
	LogRetentionDays *int32 `json:"log_retention_days,omitempty"`
}

type _YSQLAuditConfig YSQLAuditConfig

// NewYSQLAuditConfig instantiates a new YSQLAuditConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewYSQLAuditConfig(enabled bool, logCatalog bool, logClient bool, logParameter bool, logRelation bool, logRows bool, logStatement bool, logStatementOnce bool) *YSQLAuditConfig {
	this := YSQLAuditConfig{}
	this.Enabled = enabled
	this.LogCatalog = logCatalog
	this.LogClient = logClient
	this.LogParameter = logParameter
	this.LogRelation = logRelation
	this.LogRows = logRows
	this.LogStatement = logStatement
	this.LogStatementOnce = logStatementOnce
	return &this
}

// NewYSQLAuditConfigWithDefaults instantiates a new YSQLAuditConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewYSQLAuditConfigWithDefaults() *YSQLAuditConfig {
	this := YSQLAuditConfig{}
	return &this
}

// GetClasses returns the Classes field value if set, zero value otherwise.
func (o *YSQLAuditConfig) GetClasses() []string {
	if o == nil || IsNil(o.Classes) {
		var ret []string
		return ret
	}
	return o.Classes
}

// GetClassesOk returns a tuple with the Classes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *YSQLAuditConfig) GetClassesOk() ([]string, bool) {
	if o == nil || IsNil(o.Classes) {
		return nil, false
	}
	return o.Classes, true
}

// HasClasses returns a boolean if a field has been set.
func (o *YSQLAuditConfig) HasClasses() bool {
	if o != nil && !IsNil(o.Classes) {
		return true
	}

	return false
}

// SetClasses gets a reference to the given []string and assigns it to the Classes field.
func (o *YSQLAuditConfig) SetClasses(v []string) {
	o.Classes = v
}

// GetEnabled returns the Enabled field value
func (o *YSQLAuditConfig) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *YSQLAuditConfig) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *YSQLAuditConfig) SetEnabled(v bool) {
	o.Enabled = v
}

// GetLogCatalog returns the LogCatalog field value
func (o *YSQLAuditConfig) GetLogCatalog() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.LogCatalog
}

// GetLogCatalogOk returns a tuple with the LogCatalog field value
// and a boolean to check if the value has been set.
func (o *YSQLAuditConfig) GetLogCatalogOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LogCatalog, true
}

// SetLogCatalog sets field value
func (o *YSQLAuditConfig) SetLogCatalog(v bool) {
	o.LogCatalog = v
}

// GetLogClient returns the LogClient field value
func (o *YSQLAuditConfig) GetLogClient() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.LogClient
}

// GetLogClientOk returns a tuple with the LogClient field value
// and a boolean to check if the value has been set.
func (o *YSQLAuditConfig) GetLogClientOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LogClient, true
}

// SetLogClient sets field value
func (o *YSQLAuditConfig) SetLogClient(v bool) {
	o.LogClient = v
}

// GetLogLevel returns the LogLevel field value if set, zero value otherwise.
func (o *YSQLAuditConfig) GetLogLevel() string {
	if o == nil || IsNil(o.LogLevel) {
		var ret string
		return ret
	}
	return *o.LogLevel
}

// GetLogLevelOk returns a tuple with the LogLevel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *YSQLAuditConfig) GetLogLevelOk() (*string, bool) {
	if o == nil || IsNil(o.LogLevel) {
		return nil, false
	}
	return o.LogLevel, true
}

// HasLogLevel returns a boolean if a field has been set.
func (o *YSQLAuditConfig) HasLogLevel() bool {
	if o != nil && !IsNil(o.LogLevel) {
		return true
	}

	return false
}

// SetLogLevel gets a reference to the given string and assigns it to the LogLevel field.
func (o *YSQLAuditConfig) SetLogLevel(v string) {
	o.LogLevel = &v
}

// GetLogParameter returns the LogParameter field value
func (o *YSQLAuditConfig) GetLogParameter() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.LogParameter
}

// GetLogParameterOk returns a tuple with the LogParameter field value
// and a boolean to check if the value has been set.
func (o *YSQLAuditConfig) GetLogParameterOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LogParameter, true
}

// SetLogParameter sets field value
func (o *YSQLAuditConfig) SetLogParameter(v bool) {
	o.LogParameter = v
}

// GetLogParameterMaxSize returns the LogParameterMaxSize field value if set, zero value otherwise.
func (o *YSQLAuditConfig) GetLogParameterMaxSize() int32 {
	if o == nil || IsNil(o.LogParameterMaxSize) {
		var ret int32
		return ret
	}
	return *o.LogParameterMaxSize
}

// GetLogParameterMaxSizeOk returns a tuple with the LogParameterMaxSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *YSQLAuditConfig) GetLogParameterMaxSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.LogParameterMaxSize) {
		return nil, false
	}
	return o.LogParameterMaxSize, true
}

// HasLogParameterMaxSize returns a boolean if a field has been set.
func (o *YSQLAuditConfig) HasLogParameterMaxSize() bool {
	if o != nil && !IsNil(o.LogParameterMaxSize) {
		return true
	}

	return false
}

// SetLogParameterMaxSize gets a reference to the given int32 and assigns it to the LogParameterMaxSize field.
func (o *YSQLAuditConfig) SetLogParameterMaxSize(v int32) {
	o.LogParameterMaxSize = &v
}

// GetLogRelation returns the LogRelation field value
func (o *YSQLAuditConfig) GetLogRelation() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.LogRelation
}

// GetLogRelationOk returns a tuple with the LogRelation field value
// and a boolean to check if the value has been set.
func (o *YSQLAuditConfig) GetLogRelationOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LogRelation, true
}

// SetLogRelation sets field value
func (o *YSQLAuditConfig) SetLogRelation(v bool) {
	o.LogRelation = v
}

// GetLogRows returns the LogRows field value
func (o *YSQLAuditConfig) GetLogRows() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.LogRows
}

// GetLogRowsOk returns a tuple with the LogRows field value
// and a boolean to check if the value has been set.
func (o *YSQLAuditConfig) GetLogRowsOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LogRows, true
}

// SetLogRows sets field value
func (o *YSQLAuditConfig) SetLogRows(v bool) {
	o.LogRows = v
}

// GetLogStatement returns the LogStatement field value
func (o *YSQLAuditConfig) GetLogStatement() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.LogStatement
}

// GetLogStatementOk returns a tuple with the LogStatement field value
// and a boolean to check if the value has been set.
func (o *YSQLAuditConfig) GetLogStatementOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LogStatement, true
}

// SetLogStatement sets field value
func (o *YSQLAuditConfig) SetLogStatement(v bool) {
	o.LogStatement = v
}

// GetLogStatementOnce returns the LogStatementOnce field value
func (o *YSQLAuditConfig) GetLogStatementOnce() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.LogStatementOnce
}

// GetLogStatementOnceOk returns a tuple with the LogStatementOnce field value
// and a boolean to check if the value has been set.
func (o *YSQLAuditConfig) GetLogStatementOnceOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LogStatementOnce, true
}

// SetLogStatementOnce sets field value
func (o *YSQLAuditConfig) SetLogStatementOnce(v bool) {
	o.LogStatementOnce = v
}

// GetLogRetentionDays returns the LogRetentionDays field value if set, zero value otherwise.
func (o *YSQLAuditConfig) GetLogRetentionDays() int32 {
	if o == nil || IsNil(o.LogRetentionDays) {
		var ret int32
		return ret
	}
	return *o.LogRetentionDays
}

// GetLogRetentionDaysOk returns a tuple with the LogRetentionDays field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *YSQLAuditConfig) GetLogRetentionDaysOk() (*int32, bool) {
	if o == nil || IsNil(o.LogRetentionDays) {
		return nil, false
	}
	return o.LogRetentionDays, true
}

// HasLogRetentionDays returns a boolean if a field has been set.
func (o *YSQLAuditConfig) HasLogRetentionDays() bool {
	if o != nil && !IsNil(o.LogRetentionDays) {
		return true
	}

	return false
}

// SetLogRetentionDays gets a reference to the given int32 and assigns it to the LogRetentionDays field.
func (o *YSQLAuditConfig) SetLogRetentionDays(v int32) {
	o.LogRetentionDays = &v
}

func (o YSQLAuditConfig) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o YSQLAuditConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Classes) {
		toSerialize["classes"] = o.Classes
	}
	toSerialize["enabled"] = o.Enabled
	toSerialize["log_catalog"] = o.LogCatalog
	toSerialize["log_client"] = o.LogClient
	if !IsNil(o.LogLevel) {
		toSerialize["log_level"] = o.LogLevel
	}
	toSerialize["log_parameter"] = o.LogParameter
	if !IsNil(o.LogParameterMaxSize) {
		toSerialize["log_parameter_max_size"] = o.LogParameterMaxSize
	}
	toSerialize["log_relation"] = o.LogRelation
	toSerialize["log_rows"] = o.LogRows
	toSerialize["log_statement"] = o.LogStatement
	toSerialize["log_statement_once"] = o.LogStatementOnce
	if !IsNil(o.LogRetentionDays) {
		toSerialize["log_retention_days"] = o.LogRetentionDays
	}
	return toSerialize, nil
}

type NullableYSQLAuditConfig struct {
	value *YSQLAuditConfig
	isSet bool
}

func (v NullableYSQLAuditConfig) Get() *YSQLAuditConfig {
	return v.value
}

func (v *NullableYSQLAuditConfig) Set(val *YSQLAuditConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableYSQLAuditConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableYSQLAuditConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableYSQLAuditConfig(val *YSQLAuditConfig) *NullableYSQLAuditConfig {
	return &NullableYSQLAuditConfig{value: val, isSet: true}
}

func (v NullableYSQLAuditConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableYSQLAuditConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
