/*
YugabyteDB Anywhere V2 APIs

An improved set of APIs for managing YugabyteDB Anywhere

API version: v2
Contact: support@yugabyte.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v2

import (
	"encoding/json"
	"time"
)

// checks if the DrConfigInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DrConfigInfo{}

// DrConfigInfo System-generated disaster recovery configuration metadata and runtime status.
type DrConfigInfo struct {
	// DR config UUID.
	Uuid *string `json:"uuid,omitempty"`
	// High-level lifecycle state of the DR config.
	State                  *string                           `json:"state,omitempty"`
	PrimaryUniverseState   *DrConfigUniverseReplicationState `json:"primary_universe_state,omitempty"`
	DrReplicaUniverseState *DrConfigUniverseReplicationState `json:"dr_replica_universe_state,omitempty"`
	// Keyspace name that the current DR task is working on, if any.
	KeyspacePending *string `json:"keyspace_pending,omitempty"`
	// Time when the DR config was created.
	CreateTime *time.Time `json:"create_time,omitempty"`
	// Time when the DR config was last modified.
	ModifyTime *time.Time `json:"modify_time,omitempty"`
	// Replication group name in the DR replica universe cluster config.
	ReplicationGroupName *string `json:"replication_group_name,omitempty"`
	// Whether the primary universe is active in replication.
	PrimaryUniverseActive *bool `json:"primary_universe_active,omitempty"`
	// Whether the DR replica universe is active in replication.
	DrReplicaUniverseActive *bool `json:"dr_replica_universe_active,omitempty"`
}

// NewDrConfigInfo instantiates a new DrConfigInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDrConfigInfo() *DrConfigInfo {
	this := DrConfigInfo{}
	return &this
}

// NewDrConfigInfoWithDefaults instantiates a new DrConfigInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDrConfigInfoWithDefaults() *DrConfigInfo {
	this := DrConfigInfo{}
	return &this
}

// GetUuid returns the Uuid field value if set, zero value otherwise.
func (o *DrConfigInfo) GetUuid() string {
	if o == nil || IsNil(o.Uuid) {
		var ret string
		return ret
	}
	return *o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DrConfigInfo) GetUuidOk() (*string, bool) {
	if o == nil || IsNil(o.Uuid) {
		return nil, false
	}
	return o.Uuid, true
}

// HasUuid returns a boolean if a field has been set.
func (o *DrConfigInfo) HasUuid() bool {
	if o != nil && !IsNil(o.Uuid) {
		return true
	}

	return false
}

// SetUuid gets a reference to the given string and assigns it to the Uuid field.
func (o *DrConfigInfo) SetUuid(v string) {
	o.Uuid = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *DrConfigInfo) GetState() string {
	if o == nil || IsNil(o.State) {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DrConfigInfo) GetStateOk() (*string, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *DrConfigInfo) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *DrConfigInfo) SetState(v string) {
	o.State = &v
}

// GetPrimaryUniverseState returns the PrimaryUniverseState field value if set, zero value otherwise.
func (o *DrConfigInfo) GetPrimaryUniverseState() DrConfigUniverseReplicationState {
	if o == nil || IsNil(o.PrimaryUniverseState) {
		var ret DrConfigUniverseReplicationState
		return ret
	}
	return *o.PrimaryUniverseState
}

// GetPrimaryUniverseStateOk returns a tuple with the PrimaryUniverseState field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DrConfigInfo) GetPrimaryUniverseStateOk() (*DrConfigUniverseReplicationState, bool) {
	if o == nil || IsNil(o.PrimaryUniverseState) {
		return nil, false
	}
	return o.PrimaryUniverseState, true
}

// HasPrimaryUniverseState returns a boolean if a field has been set.
func (o *DrConfigInfo) HasPrimaryUniverseState() bool {
	if o != nil && !IsNil(o.PrimaryUniverseState) {
		return true
	}

	return false
}

// SetPrimaryUniverseState gets a reference to the given DrConfigUniverseReplicationState and assigns it to the PrimaryUniverseState field.
func (o *DrConfigInfo) SetPrimaryUniverseState(v DrConfigUniverseReplicationState) {
	o.PrimaryUniverseState = &v
}

// GetDrReplicaUniverseState returns the DrReplicaUniverseState field value if set, zero value otherwise.
func (o *DrConfigInfo) GetDrReplicaUniverseState() DrConfigUniverseReplicationState {
	if o == nil || IsNil(o.DrReplicaUniverseState) {
		var ret DrConfigUniverseReplicationState
		return ret
	}
	return *o.DrReplicaUniverseState
}

// GetDrReplicaUniverseStateOk returns a tuple with the DrReplicaUniverseState field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DrConfigInfo) GetDrReplicaUniverseStateOk() (*DrConfigUniverseReplicationState, bool) {
	if o == nil || IsNil(o.DrReplicaUniverseState) {
		return nil, false
	}
	return o.DrReplicaUniverseState, true
}

// HasDrReplicaUniverseState returns a boolean if a field has been set.
func (o *DrConfigInfo) HasDrReplicaUniverseState() bool {
	if o != nil && !IsNil(o.DrReplicaUniverseState) {
		return true
	}

	return false
}

// SetDrReplicaUniverseState gets a reference to the given DrConfigUniverseReplicationState and assigns it to the DrReplicaUniverseState field.
func (o *DrConfigInfo) SetDrReplicaUniverseState(v DrConfigUniverseReplicationState) {
	o.DrReplicaUniverseState = &v
}

// GetKeyspacePending returns the KeyspacePending field value if set, zero value otherwise.
func (o *DrConfigInfo) GetKeyspacePending() string {
	if o == nil || IsNil(o.KeyspacePending) {
		var ret string
		return ret
	}
	return *o.KeyspacePending
}

// GetKeyspacePendingOk returns a tuple with the KeyspacePending field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DrConfigInfo) GetKeyspacePendingOk() (*string, bool) {
	if o == nil || IsNil(o.KeyspacePending) {
		return nil, false
	}
	return o.KeyspacePending, true
}

// HasKeyspacePending returns a boolean if a field has been set.
func (o *DrConfigInfo) HasKeyspacePending() bool {
	if o != nil && !IsNil(o.KeyspacePending) {
		return true
	}

	return false
}

// SetKeyspacePending gets a reference to the given string and assigns it to the KeyspacePending field.
func (o *DrConfigInfo) SetKeyspacePending(v string) {
	o.KeyspacePending = &v
}

// GetCreateTime returns the CreateTime field value if set, zero value otherwise.
func (o *DrConfigInfo) GetCreateTime() time.Time {
	if o == nil || IsNil(o.CreateTime) {
		var ret time.Time
		return ret
	}
	return *o.CreateTime
}

// GetCreateTimeOk returns a tuple with the CreateTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DrConfigInfo) GetCreateTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreateTime) {
		return nil, false
	}
	return o.CreateTime, true
}

// HasCreateTime returns a boolean if a field has been set.
func (o *DrConfigInfo) HasCreateTime() bool {
	if o != nil && !IsNil(o.CreateTime) {
		return true
	}

	return false
}

// SetCreateTime gets a reference to the given time.Time and assigns it to the CreateTime field.
func (o *DrConfigInfo) SetCreateTime(v time.Time) {
	o.CreateTime = &v
}

// GetModifyTime returns the ModifyTime field value if set, zero value otherwise.
func (o *DrConfigInfo) GetModifyTime() time.Time {
	if o == nil || IsNil(o.ModifyTime) {
		var ret time.Time
		return ret
	}
	return *o.ModifyTime
}

// GetModifyTimeOk returns a tuple with the ModifyTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DrConfigInfo) GetModifyTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ModifyTime) {
		return nil, false
	}
	return o.ModifyTime, true
}

// HasModifyTime returns a boolean if a field has been set.
func (o *DrConfigInfo) HasModifyTime() bool {
	if o != nil && !IsNil(o.ModifyTime) {
		return true
	}

	return false
}

// SetModifyTime gets a reference to the given time.Time and assigns it to the ModifyTime field.
func (o *DrConfigInfo) SetModifyTime(v time.Time) {
	o.ModifyTime = &v
}

// GetReplicationGroupName returns the ReplicationGroupName field value if set, zero value otherwise.
func (o *DrConfigInfo) GetReplicationGroupName() string {
	if o == nil || IsNil(o.ReplicationGroupName) {
		var ret string
		return ret
	}
	return *o.ReplicationGroupName
}

// GetReplicationGroupNameOk returns a tuple with the ReplicationGroupName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DrConfigInfo) GetReplicationGroupNameOk() (*string, bool) {
	if o == nil || IsNil(o.ReplicationGroupName) {
		return nil, false
	}
	return o.ReplicationGroupName, true
}

// HasReplicationGroupName returns a boolean if a field has been set.
func (o *DrConfigInfo) HasReplicationGroupName() bool {
	if o != nil && !IsNil(o.ReplicationGroupName) {
		return true
	}

	return false
}

// SetReplicationGroupName gets a reference to the given string and assigns it to the ReplicationGroupName field.
func (o *DrConfigInfo) SetReplicationGroupName(v string) {
	o.ReplicationGroupName = &v
}

// GetPrimaryUniverseActive returns the PrimaryUniverseActive field value if set, zero value otherwise.
func (o *DrConfigInfo) GetPrimaryUniverseActive() bool {
	if o == nil || IsNil(o.PrimaryUniverseActive) {
		var ret bool
		return ret
	}
	return *o.PrimaryUniverseActive
}

// GetPrimaryUniverseActiveOk returns a tuple with the PrimaryUniverseActive field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DrConfigInfo) GetPrimaryUniverseActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.PrimaryUniverseActive) {
		return nil, false
	}
	return o.PrimaryUniverseActive, true
}

// HasPrimaryUniverseActive returns a boolean if a field has been set.
func (o *DrConfigInfo) HasPrimaryUniverseActive() bool {
	if o != nil && !IsNil(o.PrimaryUniverseActive) {
		return true
	}

	return false
}

// SetPrimaryUniverseActive gets a reference to the given bool and assigns it to the PrimaryUniverseActive field.
func (o *DrConfigInfo) SetPrimaryUniverseActive(v bool) {
	o.PrimaryUniverseActive = &v
}

// GetDrReplicaUniverseActive returns the DrReplicaUniverseActive field value if set, zero value otherwise.
func (o *DrConfigInfo) GetDrReplicaUniverseActive() bool {
	if o == nil || IsNil(o.DrReplicaUniverseActive) {
		var ret bool
		return ret
	}
	return *o.DrReplicaUniverseActive
}

// GetDrReplicaUniverseActiveOk returns a tuple with the DrReplicaUniverseActive field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DrConfigInfo) GetDrReplicaUniverseActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.DrReplicaUniverseActive) {
		return nil, false
	}
	return o.DrReplicaUniverseActive, true
}

// HasDrReplicaUniverseActive returns a boolean if a field has been set.
func (o *DrConfigInfo) HasDrReplicaUniverseActive() bool {
	if o != nil && !IsNil(o.DrReplicaUniverseActive) {
		return true
	}

	return false
}

// SetDrReplicaUniverseActive gets a reference to the given bool and assigns it to the DrReplicaUniverseActive field.
func (o *DrConfigInfo) SetDrReplicaUniverseActive(v bool) {
	o.DrReplicaUniverseActive = &v
}

func (o DrConfigInfo) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DrConfigInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Uuid) {
		toSerialize["uuid"] = o.Uuid
	}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	if !IsNil(o.PrimaryUniverseState) {
		toSerialize["primary_universe_state"] = o.PrimaryUniverseState
	}
	if !IsNil(o.DrReplicaUniverseState) {
		toSerialize["dr_replica_universe_state"] = o.DrReplicaUniverseState
	}
	if !IsNil(o.KeyspacePending) {
		toSerialize["keyspace_pending"] = o.KeyspacePending
	}
	if !IsNil(o.CreateTime) {
		toSerialize["create_time"] = o.CreateTime
	}
	if !IsNil(o.ModifyTime) {
		toSerialize["modify_time"] = o.ModifyTime
	}
	if !IsNil(o.ReplicationGroupName) {
		toSerialize["replication_group_name"] = o.ReplicationGroupName
	}
	if !IsNil(o.PrimaryUniverseActive) {
		toSerialize["primary_universe_active"] = o.PrimaryUniverseActive
	}
	if !IsNil(o.DrReplicaUniverseActive) {
		toSerialize["dr_replica_universe_active"] = o.DrReplicaUniverseActive
	}
	return toSerialize, nil
}

type NullableDrConfigInfo struct {
	value *DrConfigInfo
	isSet bool
}

func (v NullableDrConfigInfo) Get() *DrConfigInfo {
	return v.value
}

func (v *NullableDrConfigInfo) Set(val *DrConfigInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableDrConfigInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableDrConfigInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDrConfigInfo(val *DrConfigInfo) *NullableDrConfigInfo {
	return &NullableDrConfigInfo{value: val, isSet: true}
}

func (v NullableDrConfigInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDrConfigInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
