/*
YugabyteDB Anywhere V2 APIs

An improved set of APIs for managing YugabyteDB Anywhere

API version: v2
Contact: support@yugabyte.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v2

import (
	"encoding/json"
	"fmt"
)

// ScrapeConfigTargetType Enum for target types that support metrics export scrape configuration. 
type ScrapeConfigTargetType string

// List of ScrapeConfigTargetType
const (
	MASTER_EXPORT ScrapeConfigTargetType = "MASTER_EXPORT"
	TSERVER_EXPORT ScrapeConfigTargetType = "TSERVER_EXPORT"
	YSQL_EXPORT ScrapeConfigTargetType = "YSQL_EXPORT"
	CQL_EXPORT ScrapeConfigTargetType = "CQL_EXPORT"
	NODE_EXPORT ScrapeConfigTargetType = "NODE_EXPORT"
	NODE_AGENT_EXPORT ScrapeConfigTargetType = "NODE_AGENT_EXPORT"
	OTEL_EXPORT ScrapeConfigTargetType = "OTEL_EXPORT"
)

// All allowed values of ScrapeConfigTargetType enum
var AllowedScrapeConfigTargetTypeEnumValues = []ScrapeConfigTargetType{
	"MASTER_EXPORT",
	"TSERVER_EXPORT",
	"YSQL_EXPORT",
	"CQL_EXPORT",
	"NODE_EXPORT",
	"NODE_AGENT_EXPORT",
	"OTEL_EXPORT",
}

func (v *ScrapeConfigTargetType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ScrapeConfigTargetType(value)
	for _, existing := range AllowedScrapeConfigTargetTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ScrapeConfigTargetType", value)
}

// NewScrapeConfigTargetTypeFromValue returns a pointer to a valid ScrapeConfigTargetType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewScrapeConfigTargetTypeFromValue(v string) (*ScrapeConfigTargetType, error) {
	ev := ScrapeConfigTargetType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ScrapeConfigTargetType: valid values are %v", v, AllowedScrapeConfigTargetTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ScrapeConfigTargetType) IsValid() bool {
	for _, existing := range AllowedScrapeConfigTargetTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ScrapeConfigTargetType value
func (v ScrapeConfigTargetType) Ptr() *ScrapeConfigTargetType {
	return &v
}

type NullableScrapeConfigTargetType struct {
	value *ScrapeConfigTargetType
	isSet bool
}

func (v NullableScrapeConfigTargetType) Get() *ScrapeConfigTargetType {
	return v.value
}

func (v *NullableScrapeConfigTargetType) Set(val *ScrapeConfigTargetType) {
	v.value = val
	v.isSet = true
}

func (v NullableScrapeConfigTargetType) IsSet() bool {
	return v.isSet
}

func (v *NullableScrapeConfigTargetType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScrapeConfigTargetType(val *ScrapeConfigTargetType) *NullableScrapeConfigTargetType {
	return &NullableScrapeConfigTargetType{value: val, isSet: true}
}

func (v NullableScrapeConfigTargetType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScrapeConfigTargetType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

