/*
YugabyteDB Anywhere V2 APIs

An improved set of APIs for managing YugabyteDB Anywhere

API version: v2
Contact: support@yugabyte.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v2

import (
	"encoding/json"
)

// checks if the ClusterResizeNodeSpec type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClusterResizeNodeSpec{}

// ClusterResizeNodeSpec Node settings (like CPU / memory) for each node in the cluster. The node settings configured at top-level are uniform settings for both tserver and master nodes. Granular settings for tserver and master (honoured if dedicated_nodes is true or this is k8s cluster) are available for certain node properties. Granular settings can also be overridden per Availability Zone. This is part of ClusterSpec.
type ClusterResizeNodeSpec struct {
	// Instance type for tserver/master nodes of cluster that determines the cpu and memory resources.
	InstanceType *string                   `json:"instance_type,omitempty"`
	StorageSpec  *ClusterResizeStorageSpec `json:"storage_spec,omitempty"`
	// Amount of memory in MB to limit the postgres process using the ysql cgroup. The value should be greater than 0. When set to 0 it results in no cgroup limits. For a read replica cluster, setting this value to null or -1 would inherit this value from the primary cluster. Applicable only for nodes running as Linux VMs on AWS/GCP/Azure Cloud Provider. Only used internally by YBM.
	CgroupSize             *int32                    `json:"cgroup_size,omitempty"`
	Tserver                *PerProcessResizeNodeSpec `json:"tserver,omitempty"`
	Master                 *PerProcessResizeNodeSpec `json:"master,omitempty"`
	K8sMasterResourceSpec  *K8SNodeResourceSpec      `json:"k8s_master_resource_spec,omitempty"`
	K8sTserverResourceSpec *K8SNodeResourceSpec      `json:"k8s_tserver_resource_spec,omitempty"`
	// Granular node settings overridden per Availability Zone identified by AZ uuid.
	AzNodeSpec *map[string]AvailabilityZoneResizeNodeSpec `json:"az_node_spec,omitempty"`
}

// NewClusterResizeNodeSpec instantiates a new ClusterResizeNodeSpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClusterResizeNodeSpec() *ClusterResizeNodeSpec {
	this := ClusterResizeNodeSpec{}
	return &this
}

// NewClusterResizeNodeSpecWithDefaults instantiates a new ClusterResizeNodeSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClusterResizeNodeSpecWithDefaults() *ClusterResizeNodeSpec {
	this := ClusterResizeNodeSpec{}
	return &this
}

// GetInstanceType returns the InstanceType field value if set, zero value otherwise.
func (o *ClusterResizeNodeSpec) GetInstanceType() string {
	if o == nil || IsNil(o.InstanceType) {
		var ret string
		return ret
	}
	return *o.InstanceType
}

// GetInstanceTypeOk returns a tuple with the InstanceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterResizeNodeSpec) GetInstanceTypeOk() (*string, bool) {
	if o == nil || IsNil(o.InstanceType) {
		return nil, false
	}
	return o.InstanceType, true
}

// HasInstanceType returns a boolean if a field has been set.
func (o *ClusterResizeNodeSpec) HasInstanceType() bool {
	if o != nil && !IsNil(o.InstanceType) {
		return true
	}

	return false
}

// SetInstanceType gets a reference to the given string and assigns it to the InstanceType field.
func (o *ClusterResizeNodeSpec) SetInstanceType(v string) {
	o.InstanceType = &v
}

// GetStorageSpec returns the StorageSpec field value if set, zero value otherwise.
func (o *ClusterResizeNodeSpec) GetStorageSpec() ClusterResizeStorageSpec {
	if o == nil || IsNil(o.StorageSpec) {
		var ret ClusterResizeStorageSpec
		return ret
	}
	return *o.StorageSpec
}

// GetStorageSpecOk returns a tuple with the StorageSpec field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterResizeNodeSpec) GetStorageSpecOk() (*ClusterResizeStorageSpec, bool) {
	if o == nil || IsNil(o.StorageSpec) {
		return nil, false
	}
	return o.StorageSpec, true
}

// HasStorageSpec returns a boolean if a field has been set.
func (o *ClusterResizeNodeSpec) HasStorageSpec() bool {
	if o != nil && !IsNil(o.StorageSpec) {
		return true
	}

	return false
}

// SetStorageSpec gets a reference to the given ClusterResizeStorageSpec and assigns it to the StorageSpec field.
func (o *ClusterResizeNodeSpec) SetStorageSpec(v ClusterResizeStorageSpec) {
	o.StorageSpec = &v
}

// GetCgroupSize returns the CgroupSize field value if set, zero value otherwise.
func (o *ClusterResizeNodeSpec) GetCgroupSize() int32 {
	if o == nil || IsNil(o.CgroupSize) {
		var ret int32
		return ret
	}
	return *o.CgroupSize
}

// GetCgroupSizeOk returns a tuple with the CgroupSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterResizeNodeSpec) GetCgroupSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.CgroupSize) {
		return nil, false
	}
	return o.CgroupSize, true
}

// HasCgroupSize returns a boolean if a field has been set.
func (o *ClusterResizeNodeSpec) HasCgroupSize() bool {
	if o != nil && !IsNil(o.CgroupSize) {
		return true
	}

	return false
}

// SetCgroupSize gets a reference to the given int32 and assigns it to the CgroupSize field.
func (o *ClusterResizeNodeSpec) SetCgroupSize(v int32) {
	o.CgroupSize = &v
}

// GetTserver returns the Tserver field value if set, zero value otherwise.
func (o *ClusterResizeNodeSpec) GetTserver() PerProcessResizeNodeSpec {
	if o == nil || IsNil(o.Tserver) {
		var ret PerProcessResizeNodeSpec
		return ret
	}
	return *o.Tserver
}

// GetTserverOk returns a tuple with the Tserver field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterResizeNodeSpec) GetTserverOk() (*PerProcessResizeNodeSpec, bool) {
	if o == nil || IsNil(o.Tserver) {
		return nil, false
	}
	return o.Tserver, true
}

// HasTserver returns a boolean if a field has been set.
func (o *ClusterResizeNodeSpec) HasTserver() bool {
	if o != nil && !IsNil(o.Tserver) {
		return true
	}

	return false
}

// SetTserver gets a reference to the given PerProcessResizeNodeSpec and assigns it to the Tserver field.
func (o *ClusterResizeNodeSpec) SetTserver(v PerProcessResizeNodeSpec) {
	o.Tserver = &v
}

// GetMaster returns the Master field value if set, zero value otherwise.
func (o *ClusterResizeNodeSpec) GetMaster() PerProcessResizeNodeSpec {
	if o == nil || IsNil(o.Master) {
		var ret PerProcessResizeNodeSpec
		return ret
	}
	return *o.Master
}

// GetMasterOk returns a tuple with the Master field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterResizeNodeSpec) GetMasterOk() (*PerProcessResizeNodeSpec, bool) {
	if o == nil || IsNil(o.Master) {
		return nil, false
	}
	return o.Master, true
}

// HasMaster returns a boolean if a field has been set.
func (o *ClusterResizeNodeSpec) HasMaster() bool {
	if o != nil && !IsNil(o.Master) {
		return true
	}

	return false
}

// SetMaster gets a reference to the given PerProcessResizeNodeSpec and assigns it to the Master field.
func (o *ClusterResizeNodeSpec) SetMaster(v PerProcessResizeNodeSpec) {
	o.Master = &v
}

// GetK8sMasterResourceSpec returns the K8sMasterResourceSpec field value if set, zero value otherwise.
func (o *ClusterResizeNodeSpec) GetK8sMasterResourceSpec() K8SNodeResourceSpec {
	if o == nil || IsNil(o.K8sMasterResourceSpec) {
		var ret K8SNodeResourceSpec
		return ret
	}
	return *o.K8sMasterResourceSpec
}

// GetK8sMasterResourceSpecOk returns a tuple with the K8sMasterResourceSpec field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterResizeNodeSpec) GetK8sMasterResourceSpecOk() (*K8SNodeResourceSpec, bool) {
	if o == nil || IsNil(o.K8sMasterResourceSpec) {
		return nil, false
	}
	return o.K8sMasterResourceSpec, true
}

// HasK8sMasterResourceSpec returns a boolean if a field has been set.
func (o *ClusterResizeNodeSpec) HasK8sMasterResourceSpec() bool {
	if o != nil && !IsNil(o.K8sMasterResourceSpec) {
		return true
	}

	return false
}

// SetK8sMasterResourceSpec gets a reference to the given K8SNodeResourceSpec and assigns it to the K8sMasterResourceSpec field.
func (o *ClusterResizeNodeSpec) SetK8sMasterResourceSpec(v K8SNodeResourceSpec) {
	o.K8sMasterResourceSpec = &v
}

// GetK8sTserverResourceSpec returns the K8sTserverResourceSpec field value if set, zero value otherwise.
func (o *ClusterResizeNodeSpec) GetK8sTserverResourceSpec() K8SNodeResourceSpec {
	if o == nil || IsNil(o.K8sTserverResourceSpec) {
		var ret K8SNodeResourceSpec
		return ret
	}
	return *o.K8sTserverResourceSpec
}

// GetK8sTserverResourceSpecOk returns a tuple with the K8sTserverResourceSpec field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterResizeNodeSpec) GetK8sTserverResourceSpecOk() (*K8SNodeResourceSpec, bool) {
	if o == nil || IsNil(o.K8sTserverResourceSpec) {
		return nil, false
	}
	return o.K8sTserverResourceSpec, true
}

// HasK8sTserverResourceSpec returns a boolean if a field has been set.
func (o *ClusterResizeNodeSpec) HasK8sTserverResourceSpec() bool {
	if o != nil && !IsNil(o.K8sTserverResourceSpec) {
		return true
	}

	return false
}

// SetK8sTserverResourceSpec gets a reference to the given K8SNodeResourceSpec and assigns it to the K8sTserverResourceSpec field.
func (o *ClusterResizeNodeSpec) SetK8sTserverResourceSpec(v K8SNodeResourceSpec) {
	o.K8sTserverResourceSpec = &v
}

// GetAzNodeSpec returns the AzNodeSpec field value if set, zero value otherwise.
func (o *ClusterResizeNodeSpec) GetAzNodeSpec() map[string]AvailabilityZoneResizeNodeSpec {
	if o == nil || IsNil(o.AzNodeSpec) {
		var ret map[string]AvailabilityZoneResizeNodeSpec
		return ret
	}
	return *o.AzNodeSpec
}

// GetAzNodeSpecOk returns a tuple with the AzNodeSpec field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterResizeNodeSpec) GetAzNodeSpecOk() (*map[string]AvailabilityZoneResizeNodeSpec, bool) {
	if o == nil || IsNil(o.AzNodeSpec) {
		return nil, false
	}
	return o.AzNodeSpec, true
}

// HasAzNodeSpec returns a boolean if a field has been set.
func (o *ClusterResizeNodeSpec) HasAzNodeSpec() bool {
	if o != nil && !IsNil(o.AzNodeSpec) {
		return true
	}

	return false
}

// SetAzNodeSpec gets a reference to the given map[string]AvailabilityZoneResizeNodeSpec and assigns it to the AzNodeSpec field.
func (o *ClusterResizeNodeSpec) SetAzNodeSpec(v map[string]AvailabilityZoneResizeNodeSpec) {
	o.AzNodeSpec = &v
}

func (o ClusterResizeNodeSpec) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClusterResizeNodeSpec) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.InstanceType) {
		toSerialize["instance_type"] = o.InstanceType
	}
	if !IsNil(o.StorageSpec) {
		toSerialize["storage_spec"] = o.StorageSpec
	}
	if !IsNil(o.CgroupSize) {
		toSerialize["cgroup_size"] = o.CgroupSize
	}
	if !IsNil(o.Tserver) {
		toSerialize["tserver"] = o.Tserver
	}
	if !IsNil(o.Master) {
		toSerialize["master"] = o.Master
	}
	if !IsNil(o.K8sMasterResourceSpec) {
		toSerialize["k8s_master_resource_spec"] = o.K8sMasterResourceSpec
	}
	if !IsNil(o.K8sTserverResourceSpec) {
		toSerialize["k8s_tserver_resource_spec"] = o.K8sTserverResourceSpec
	}
	if !IsNil(o.AzNodeSpec) {
		toSerialize["az_node_spec"] = o.AzNodeSpec
	}
	return toSerialize, nil
}

type NullableClusterResizeNodeSpec struct {
	value *ClusterResizeNodeSpec
	isSet bool
}

func (v NullableClusterResizeNodeSpec) Get() *ClusterResizeNodeSpec {
	return v.value
}

func (v *NullableClusterResizeNodeSpec) Set(val *ClusterResizeNodeSpec) {
	v.value = val
	v.isSet = true
}

func (v NullableClusterResizeNodeSpec) IsSet() bool {
	return v.isSet
}

func (v *NullableClusterResizeNodeSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClusterResizeNodeSpec(val *ClusterResizeNodeSpec) *NullableClusterResizeNodeSpec {
	return &NullableClusterResizeNodeSpec{value: val, isSet: true}
}

func (v NullableClusterResizeNodeSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClusterResizeNodeSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
