/*
YugabyteDB Anywhere V2 APIs

An improved set of APIs for managing YugabyteDB Anywhere

API version: v2
Contact: support@yugabyte.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v2

import (
	"encoding/json"
)

// checks if the TelemetryConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TelemetryConfig{}

// TelemetryConfig Telemetry config. Each property is optional. Set to null or omit to disable that config. Empty object = disable all.
type TelemetryConfig struct {
	AuditLogs *AuditLogsTelemetrySpec `json:"audit_logs,omitempty"`
	QueryLogs *QueryLogsTelemetrySpec `json:"query_logs,omitempty"`
	Metrics   *MetricsTelemetrySpec   `json:"metrics,omitempty"`
}

// NewTelemetryConfig instantiates a new TelemetryConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTelemetryConfig() *TelemetryConfig {
	this := TelemetryConfig{}
	return &this
}

// NewTelemetryConfigWithDefaults instantiates a new TelemetryConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTelemetryConfigWithDefaults() *TelemetryConfig {
	this := TelemetryConfig{}
	return &this
}

// GetAuditLogs returns the AuditLogs field value if set, zero value otherwise.
func (o *TelemetryConfig) GetAuditLogs() AuditLogsTelemetrySpec {
	if o == nil || IsNil(o.AuditLogs) {
		var ret AuditLogsTelemetrySpec
		return ret
	}
	return *o.AuditLogs
}

// GetAuditLogsOk returns a tuple with the AuditLogs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TelemetryConfig) GetAuditLogsOk() (*AuditLogsTelemetrySpec, bool) {
	if o == nil || IsNil(o.AuditLogs) {
		return nil, false
	}
	return o.AuditLogs, true
}

// HasAuditLogs returns a boolean if a field has been set.
func (o *TelemetryConfig) HasAuditLogs() bool {
	if o != nil && !IsNil(o.AuditLogs) {
		return true
	}

	return false
}

// SetAuditLogs gets a reference to the given AuditLogsTelemetrySpec and assigns it to the AuditLogs field.
func (o *TelemetryConfig) SetAuditLogs(v AuditLogsTelemetrySpec) {
	o.AuditLogs = &v
}

// GetQueryLogs returns the QueryLogs field value if set, zero value otherwise.
func (o *TelemetryConfig) GetQueryLogs() QueryLogsTelemetrySpec {
	if o == nil || IsNil(o.QueryLogs) {
		var ret QueryLogsTelemetrySpec
		return ret
	}
	return *o.QueryLogs
}

// GetQueryLogsOk returns a tuple with the QueryLogs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TelemetryConfig) GetQueryLogsOk() (*QueryLogsTelemetrySpec, bool) {
	if o == nil || IsNil(o.QueryLogs) {
		return nil, false
	}
	return o.QueryLogs, true
}

// HasQueryLogs returns a boolean if a field has been set.
func (o *TelemetryConfig) HasQueryLogs() bool {
	if o != nil && !IsNil(o.QueryLogs) {
		return true
	}

	return false
}

// SetQueryLogs gets a reference to the given QueryLogsTelemetrySpec and assigns it to the QueryLogs field.
func (o *TelemetryConfig) SetQueryLogs(v QueryLogsTelemetrySpec) {
	o.QueryLogs = &v
}

// GetMetrics returns the Metrics field value if set, zero value otherwise.
func (o *TelemetryConfig) GetMetrics() MetricsTelemetrySpec {
	if o == nil || IsNil(o.Metrics) {
		var ret MetricsTelemetrySpec
		return ret
	}
	return *o.Metrics
}

// GetMetricsOk returns a tuple with the Metrics field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TelemetryConfig) GetMetricsOk() (*MetricsTelemetrySpec, bool) {
	if o == nil || IsNil(o.Metrics) {
		return nil, false
	}
	return o.Metrics, true
}

// HasMetrics returns a boolean if a field has been set.
func (o *TelemetryConfig) HasMetrics() bool {
	if o != nil && !IsNil(o.Metrics) {
		return true
	}

	return false
}

// SetMetrics gets a reference to the given MetricsTelemetrySpec and assigns it to the Metrics field.
func (o *TelemetryConfig) SetMetrics(v MetricsTelemetrySpec) {
	o.Metrics = &v
}

func (o TelemetryConfig) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TelemetryConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AuditLogs) {
		toSerialize["audit_logs"] = o.AuditLogs
	}
	if !IsNil(o.QueryLogs) {
		toSerialize["query_logs"] = o.QueryLogs
	}
	if !IsNil(o.Metrics) {
		toSerialize["metrics"] = o.Metrics
	}
	return toSerialize, nil
}

type NullableTelemetryConfig struct {
	value *TelemetryConfig
	isSet bool
}

func (v NullableTelemetryConfig) Get() *TelemetryConfig {
	return v.value
}

func (v *NullableTelemetryConfig) Set(val *TelemetryConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableTelemetryConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableTelemetryConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTelemetryConfig(val *TelemetryConfig) *NullableTelemetryConfig {
	return &NullableTelemetryConfig{value: val, isSet: true}
}

func (v NullableTelemetryConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTelemetryConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
