/*
YugabyteDB Anywhere V2 APIs

An improved set of APIs for managing YugabyteDB Anywhere

API version: v2
Contact: support@yugabyte.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v2

import (
	"encoding/json"
)

// checks if the TaskVersionNumbers type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TaskVersionNumbers{}

// TaskVersionNumbers YB software version information for upgrade-related tasks.
type TaskVersionNumbers struct {
	// YB software version before the upgrade started.
	YbPrevSoftwareVersion *string `json:"yb_prev_software_version,omitempty"`
	// Target YB software version for the upgrade.
	YbSoftwareVersion *string `json:"yb_software_version,omitempty"`
}

// NewTaskVersionNumbers instantiates a new TaskVersionNumbers object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTaskVersionNumbers() *TaskVersionNumbers {
	this := TaskVersionNumbers{}
	return &this
}

// NewTaskVersionNumbersWithDefaults instantiates a new TaskVersionNumbers object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTaskVersionNumbersWithDefaults() *TaskVersionNumbers {
	this := TaskVersionNumbers{}
	return &this
}

// GetYbPrevSoftwareVersion returns the YbPrevSoftwareVersion field value if set, zero value otherwise.
func (o *TaskVersionNumbers) GetYbPrevSoftwareVersion() string {
	if o == nil || IsNil(o.YbPrevSoftwareVersion) {
		var ret string
		return ret
	}
	return *o.YbPrevSoftwareVersion
}

// GetYbPrevSoftwareVersionOk returns a tuple with the YbPrevSoftwareVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaskVersionNumbers) GetYbPrevSoftwareVersionOk() (*string, bool) {
	if o == nil || IsNil(o.YbPrevSoftwareVersion) {
		return nil, false
	}
	return o.YbPrevSoftwareVersion, true
}

// HasYbPrevSoftwareVersion returns a boolean if a field has been set.
func (o *TaskVersionNumbers) HasYbPrevSoftwareVersion() bool {
	if o != nil && !IsNil(o.YbPrevSoftwareVersion) {
		return true
	}

	return false
}

// SetYbPrevSoftwareVersion gets a reference to the given string and assigns it to the YbPrevSoftwareVersion field.
func (o *TaskVersionNumbers) SetYbPrevSoftwareVersion(v string) {
	o.YbPrevSoftwareVersion = &v
}

// GetYbSoftwareVersion returns the YbSoftwareVersion field value if set, zero value otherwise.
func (o *TaskVersionNumbers) GetYbSoftwareVersion() string {
	if o == nil || IsNil(o.YbSoftwareVersion) {
		var ret string
		return ret
	}
	return *o.YbSoftwareVersion
}

// GetYbSoftwareVersionOk returns a tuple with the YbSoftwareVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaskVersionNumbers) GetYbSoftwareVersionOk() (*string, bool) {
	if o == nil || IsNil(o.YbSoftwareVersion) {
		return nil, false
	}
	return o.YbSoftwareVersion, true
}

// HasYbSoftwareVersion returns a boolean if a field has been set.
func (o *TaskVersionNumbers) HasYbSoftwareVersion() bool {
	if o != nil && !IsNil(o.YbSoftwareVersion) {
		return true
	}

	return false
}

// SetYbSoftwareVersion gets a reference to the given string and assigns it to the YbSoftwareVersion field.
func (o *TaskVersionNumbers) SetYbSoftwareVersion(v string) {
	o.YbSoftwareVersion = &v
}

func (o TaskVersionNumbers) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TaskVersionNumbers) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.YbPrevSoftwareVersion) {
		toSerialize["yb_prev_software_version"] = o.YbPrevSoftwareVersion
	}
	if !IsNil(o.YbSoftwareVersion) {
		toSerialize["yb_software_version"] = o.YbSoftwareVersion
	}
	return toSerialize, nil
}

type NullableTaskVersionNumbers struct {
	value *TaskVersionNumbers
	isSet bool
}

func (v NullableTaskVersionNumbers) Get() *TaskVersionNumbers {
	return v.value
}

func (v *NullableTaskVersionNumbers) Set(val *TaskVersionNumbers) {
	v.value = val
	v.isSet = true
}

func (v NullableTaskVersionNumbers) IsSet() bool {
	return v.isSet
}

func (v *NullableTaskVersionNumbers) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTaskVersionNumbers(val *TaskVersionNumbers) *NullableTaskVersionNumbers {
	return &NullableTaskVersionNumbers{value: val, isSet: true}
}

func (v NullableTaskVersionNumbers) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTaskVersionNumbers) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
