/*
YugabyteDB Anywhere V2 APIs

An improved set of APIs for managing YugabyteDB Anywhere

API version: v2
Contact: support@yugabyte.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v2

import (
	"encoding/json"
)

// checks if the ProviderNodeSpec type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProviderNodeSpec{}

// ProviderNodeSpec Node properties at a specific level in the provider nodes specification hierarchy. Part of ProviderRootNodesSpec.
type ProviderNodeSpec struct {
	// Instance type for tserver/master nodes that determines the cpu and memory resources.
	InstanceType *string             `json:"instance_type,omitempty"`
	StorageSpec  *ClusterStorageSpec `json:"storage_spec,omitempty"`
	// Amount of memory in MB to limit the postgres process using the ysql cgroup. The value should be greater than 0. When set to 0 it results in no cgroup limits. Applicable only for nodes running as Linux VMs on AWS/GCP/Azure Cloud Provider.
	CgroupSize          *int32               `json:"cgroup_size,omitempty"`
	BackupProxyConfig   *NodeProxyConfig     `json:"backup_proxy_config,omitempty"`
	K8sNodeResourceSpec *K8SNodeResourceSpec `json:"k8s_node_resource_spec,omitempty"`
}

// NewProviderNodeSpec instantiates a new ProviderNodeSpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProviderNodeSpec() *ProviderNodeSpec {
	this := ProviderNodeSpec{}
	return &this
}

// NewProviderNodeSpecWithDefaults instantiates a new ProviderNodeSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProviderNodeSpecWithDefaults() *ProviderNodeSpec {
	this := ProviderNodeSpec{}
	return &this
}

// GetInstanceType returns the InstanceType field value if set, zero value otherwise.
func (o *ProviderNodeSpec) GetInstanceType() string {
	if o == nil || IsNil(o.InstanceType) {
		var ret string
		return ret
	}
	return *o.InstanceType
}

// GetInstanceTypeOk returns a tuple with the InstanceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProviderNodeSpec) GetInstanceTypeOk() (*string, bool) {
	if o == nil || IsNil(o.InstanceType) {
		return nil, false
	}
	return o.InstanceType, true
}

// HasInstanceType returns a boolean if a field has been set.
func (o *ProviderNodeSpec) HasInstanceType() bool {
	if o != nil && !IsNil(o.InstanceType) {
		return true
	}

	return false
}

// SetInstanceType gets a reference to the given string and assigns it to the InstanceType field.
func (o *ProviderNodeSpec) SetInstanceType(v string) {
	o.InstanceType = &v
}

// GetStorageSpec returns the StorageSpec field value if set, zero value otherwise.
func (o *ProviderNodeSpec) GetStorageSpec() ClusterStorageSpec {
	if o == nil || IsNil(o.StorageSpec) {
		var ret ClusterStorageSpec
		return ret
	}
	return *o.StorageSpec
}

// GetStorageSpecOk returns a tuple with the StorageSpec field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProviderNodeSpec) GetStorageSpecOk() (*ClusterStorageSpec, bool) {
	if o == nil || IsNil(o.StorageSpec) {
		return nil, false
	}
	return o.StorageSpec, true
}

// HasStorageSpec returns a boolean if a field has been set.
func (o *ProviderNodeSpec) HasStorageSpec() bool {
	if o != nil && !IsNil(o.StorageSpec) {
		return true
	}

	return false
}

// SetStorageSpec gets a reference to the given ClusterStorageSpec and assigns it to the StorageSpec field.
func (o *ProviderNodeSpec) SetStorageSpec(v ClusterStorageSpec) {
	o.StorageSpec = &v
}

// GetCgroupSize returns the CgroupSize field value if set, zero value otherwise.
func (o *ProviderNodeSpec) GetCgroupSize() int32 {
	if o == nil || IsNil(o.CgroupSize) {
		var ret int32
		return ret
	}
	return *o.CgroupSize
}

// GetCgroupSizeOk returns a tuple with the CgroupSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProviderNodeSpec) GetCgroupSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.CgroupSize) {
		return nil, false
	}
	return o.CgroupSize, true
}

// HasCgroupSize returns a boolean if a field has been set.
func (o *ProviderNodeSpec) HasCgroupSize() bool {
	if o != nil && !IsNil(o.CgroupSize) {
		return true
	}

	return false
}

// SetCgroupSize gets a reference to the given int32 and assigns it to the CgroupSize field.
func (o *ProviderNodeSpec) SetCgroupSize(v int32) {
	o.CgroupSize = &v
}

// GetBackupProxyConfig returns the BackupProxyConfig field value if set, zero value otherwise.
func (o *ProviderNodeSpec) GetBackupProxyConfig() NodeProxyConfig {
	if o == nil || IsNil(o.BackupProxyConfig) {
		var ret NodeProxyConfig
		return ret
	}
	return *o.BackupProxyConfig
}

// GetBackupProxyConfigOk returns a tuple with the BackupProxyConfig field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProviderNodeSpec) GetBackupProxyConfigOk() (*NodeProxyConfig, bool) {
	if o == nil || IsNil(o.BackupProxyConfig) {
		return nil, false
	}
	return o.BackupProxyConfig, true
}

// HasBackupProxyConfig returns a boolean if a field has been set.
func (o *ProviderNodeSpec) HasBackupProxyConfig() bool {
	if o != nil && !IsNil(o.BackupProxyConfig) {
		return true
	}

	return false
}

// SetBackupProxyConfig gets a reference to the given NodeProxyConfig and assigns it to the BackupProxyConfig field.
func (o *ProviderNodeSpec) SetBackupProxyConfig(v NodeProxyConfig) {
	o.BackupProxyConfig = &v
}

// GetK8sNodeResourceSpec returns the K8sNodeResourceSpec field value if set, zero value otherwise.
func (o *ProviderNodeSpec) GetK8sNodeResourceSpec() K8SNodeResourceSpec {
	if o == nil || IsNil(o.K8sNodeResourceSpec) {
		var ret K8SNodeResourceSpec
		return ret
	}
	return *o.K8sNodeResourceSpec
}

// GetK8sNodeResourceSpecOk returns a tuple with the K8sNodeResourceSpec field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProviderNodeSpec) GetK8sNodeResourceSpecOk() (*K8SNodeResourceSpec, bool) {
	if o == nil || IsNil(o.K8sNodeResourceSpec) {
		return nil, false
	}
	return o.K8sNodeResourceSpec, true
}

// HasK8sNodeResourceSpec returns a boolean if a field has been set.
func (o *ProviderNodeSpec) HasK8sNodeResourceSpec() bool {
	if o != nil && !IsNil(o.K8sNodeResourceSpec) {
		return true
	}

	return false
}

// SetK8sNodeResourceSpec gets a reference to the given K8SNodeResourceSpec and assigns it to the K8sNodeResourceSpec field.
func (o *ProviderNodeSpec) SetK8sNodeResourceSpec(v K8SNodeResourceSpec) {
	o.K8sNodeResourceSpec = &v
}

func (o ProviderNodeSpec) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProviderNodeSpec) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.InstanceType) {
		toSerialize["instance_type"] = o.InstanceType
	}
	if !IsNil(o.StorageSpec) {
		toSerialize["storage_spec"] = o.StorageSpec
	}
	if !IsNil(o.CgroupSize) {
		toSerialize["cgroup_size"] = o.CgroupSize
	}
	if !IsNil(o.BackupProxyConfig) {
		toSerialize["backup_proxy_config"] = o.BackupProxyConfig
	}
	if !IsNil(o.K8sNodeResourceSpec) {
		toSerialize["k8s_node_resource_spec"] = o.K8sNodeResourceSpec
	}
	return toSerialize, nil
}

type NullableProviderNodeSpec struct {
	value *ProviderNodeSpec
	isSet bool
}

func (v NullableProviderNodeSpec) Get() *ProviderNodeSpec {
	return v.value
}

func (v *NullableProviderNodeSpec) Set(val *ProviderNodeSpec) {
	v.value = val
	v.isSet = true
}

func (v NullableProviderNodeSpec) IsSet() bool {
	return v.isSet
}

func (v *NullableProviderNodeSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProviderNodeSpec(val *ProviderNodeSpec) *NullableProviderNodeSpec {
	return &NullableProviderNodeSpec{value: val, isSet: true}
}

func (v NullableProviderNodeSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProviderNodeSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
