/*
YugabyteDB Anywhere V2 APIs

An improved set of APIs for managing YugabyteDB Anywhere

API version: v2
Contact: support@yugabyte.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v2

import (
	"encoding/json"
)

// checks if the ResizeProviderNodesSpec type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResizeProviderNodesSpec{}

// ResizeProviderNodesSpec Tserver and master resize node specs at a single level of the provider nodes specification hierarchy.
type ResizeProviderNodesSpec struct {
	TserverSpecification *ResizeProviderNodeSpec `json:"tserver_specification,omitempty"`
	MasterSpecification  *ResizeProviderNodeSpec `json:"master_specification,omitempty"`
}

// NewResizeProviderNodesSpec instantiates a new ResizeProviderNodesSpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResizeProviderNodesSpec() *ResizeProviderNodesSpec {
	this := ResizeProviderNodesSpec{}
	return &this
}

// NewResizeProviderNodesSpecWithDefaults instantiates a new ResizeProviderNodesSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResizeProviderNodesSpecWithDefaults() *ResizeProviderNodesSpec {
	this := ResizeProviderNodesSpec{}
	return &this
}

// GetTserverSpecification returns the TserverSpecification field value if set, zero value otherwise.
func (o *ResizeProviderNodesSpec) GetTserverSpecification() ResizeProviderNodeSpec {
	if o == nil || IsNil(o.TserverSpecification) {
		var ret ResizeProviderNodeSpec
		return ret
	}
	return *o.TserverSpecification
}

// GetTserverSpecificationOk returns a tuple with the TserverSpecification field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResizeProviderNodesSpec) GetTserverSpecificationOk() (*ResizeProviderNodeSpec, bool) {
	if o == nil || IsNil(o.TserverSpecification) {
		return nil, false
	}
	return o.TserverSpecification, true
}

// HasTserverSpecification returns a boolean if a field has been set.
func (o *ResizeProviderNodesSpec) HasTserverSpecification() bool {
	if o != nil && !IsNil(o.TserverSpecification) {
		return true
	}

	return false
}

// SetTserverSpecification gets a reference to the given ResizeProviderNodeSpec and assigns it to the TserverSpecification field.
func (o *ResizeProviderNodesSpec) SetTserverSpecification(v ResizeProviderNodeSpec) {
	o.TserverSpecification = &v
}

// GetMasterSpecification returns the MasterSpecification field value if set, zero value otherwise.
func (o *ResizeProviderNodesSpec) GetMasterSpecification() ResizeProviderNodeSpec {
	if o == nil || IsNil(o.MasterSpecification) {
		var ret ResizeProviderNodeSpec
		return ret
	}
	return *o.MasterSpecification
}

// GetMasterSpecificationOk returns a tuple with the MasterSpecification field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResizeProviderNodesSpec) GetMasterSpecificationOk() (*ResizeProviderNodeSpec, bool) {
	if o == nil || IsNil(o.MasterSpecification) {
		return nil, false
	}
	return o.MasterSpecification, true
}

// HasMasterSpecification returns a boolean if a field has been set.
func (o *ResizeProviderNodesSpec) HasMasterSpecification() bool {
	if o != nil && !IsNil(o.MasterSpecification) {
		return true
	}

	return false
}

// SetMasterSpecification gets a reference to the given ResizeProviderNodeSpec and assigns it to the MasterSpecification field.
func (o *ResizeProviderNodesSpec) SetMasterSpecification(v ResizeProviderNodeSpec) {
	o.MasterSpecification = &v
}

func (o ResizeProviderNodesSpec) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResizeProviderNodesSpec) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TserverSpecification) {
		toSerialize["tserver_specification"] = o.TserverSpecification
	}
	if !IsNil(o.MasterSpecification) {
		toSerialize["master_specification"] = o.MasterSpecification
	}
	return toSerialize, nil
}

type NullableResizeProviderNodesSpec struct {
	value *ResizeProviderNodesSpec
	isSet bool
}

func (v NullableResizeProviderNodesSpec) Get() *ResizeProviderNodesSpec {
	return v.value
}

func (v *NullableResizeProviderNodesSpec) Set(val *ResizeProviderNodesSpec) {
	v.value = val
	v.isSet = true
}

func (v NullableResizeProviderNodesSpec) IsSet() bool {
	return v.isSet
}

func (v *NullableResizeProviderNodesSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResizeProviderNodesSpec(val *ResizeProviderNodesSpec) *NullableResizeProviderNodesSpec {
	return &NullableResizeProviderNodesSpec{value: val, isSet: true}
}

func (v NullableResizeProviderNodesSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResizeProviderNodesSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
